// Mock queries module relying on DEMO_TRIPS
import type { Trip, Author } from "./types";

// --- Demo data fallback (used when Sanity is not yet configured) ---
export const DEMO_TRIPS: Trip[] = [
  {
    _id: "trip-spiti-valley",
    title: "Spiti Valley — The Cold Desert Odyssey",
    slug: "spiti-valley",
    excerpt:
      "A 10-day self-driven Himalayan road trip from Delhi through Manali, Spiti, Kinnaur, and Shimla — high passes, ancient monasteries, and the cold desert.",
    tags: ["Adventure", "Road Trip", "India", "Himalayas", "Spiti Valley"],
    country: "India",
    startDate: "2026-09-29",
    endDate: "2026-10-08",
    bestSuggestedMonth: "June – September",
    status: "published",
    viewCount: 1284,
    totalBudget: 110000,
    currency: "INR",
    tripType: "Adventure",
    readingTime: 15,
    _createdAt: "2026-08-24T00:00:00Z",
    _updatedAt: "2026-08-24T00:00:00Z",
    coverImage: undefined,
    itinerary: [
      {
        _key: "day1",
        dayNumber: 1,
        title: "New Delhi → Manali",
        date: "2026-09-29",
        summary: "The long drive north and an acclimatisation night in Manali before the high-pass crossing.",
        activities: [
          {
            _key: "a1",
            title: "Drive to Manali (~530 km)",
            description: "Fill the tank in Delhi; stop for dhaba lunch at Sundernagar or Mandi and reach Manali by evening.",
            type: "transport",
          },
          {
            _key: "a2",
            title: "Fuel and camp check",
            description: "Refuel completely in Manali—the next reliable fuel is 210 km away—and confirm Chandratal camp availability.",
            type: "activity",
          },
          {
            _key: "a3",
            title: "Overnight at Getaway Stays, Manali",
            description: "Acclimatise at 2,050 m before crossing Kunzum Pass.",
            type: "accommodation",
          },
        ],
      },
      {
        _key: "day2",
        dayNumber: 2,
        title: "Manali → Atal Tunnel → Kunzum Pass → Chandratal",
        date: "2026-09-30",
        summary: "The critical high-altitude crossing to Chandratal Lake camp via Atal Tunnel and Kunzum Pass (4,590 m).",
        activities: [
          {
            _key: "b1",
            title: "Cross Atal Tunnel and Kunzum Pass (~120 km)",
            description: "No Rohtang permit is needed. Keep the Kunzum stop brief—20 to 30 minutes maximum.",
            type: "transport",
          },
          {
            _key: "b2",
            title: "Chandratal Lake",
            description: "Visit the crescent lake at 4,300 m.",
            location: { name: "Chandratal Lake", lat: 32.481, lng: 77.617 },
            type: "sightseeing",
          },
          {
            _key: "b3",
            title: "Overnight at Parasol Camps, Chandratal",
            description: "Night temperatures can drop below -10°C; thermals and a sleeping bag are essential.",
            notes: "Start Diamox 24–48 hours beforehand only as medically advised; hydrate aggressively and avoid alcohol.",
            type: "accommodation",
          },
        ],
      },
      {
        _key: "day3",
        dayNumber: 3,
        title: "Chandratal → Losar → Kaza",
        date: "2026-10-01",
        summary: "Descend into Spiti's cold desert, refuel in Kaza, and assess everyone for altitude sickness.",
        activities: [
          {
            _key: "c1",
            title: "Drive via Losar to Kaza (~90 km)",
            description: "Descend gradually from 4,300 m to Kaza at 3,800 m, passing the first major settlement of Losar.",
            type: "transport",
          },
          {
            _key: "c2",
            title: "Fuel, supplies, and AMS check",
            description: "Fill the tank at Kaza's retail pump, explore the market, and collect supplies or a local SIM.",
            notes: "Ensure all four travellers are symptom-free before heading deeper into Spiti.",
            type: "activity",
          },
          {
            _key: "c3",
            title: "Overnight at Sakya Homestay, Kaza",
            type: "accommodation",
          },
        ],
      },
      {
        _key: "day4",
        dayNumber: 4,
        title: "Kaza High Villages Loop",
        date: "2026-10-02",
        summary: "A high-altitude loop through Spiti's remote villages, ending at Ki Monastery.",
        activities: [
          { _key: "d1", title: "Hikkim Post Office", description: "Visit the world's highest post office and send a postcard home.", type: "sightseeing" },
          { _key: "d2", title: "Komik and Langza", description: "Explore one of the world's highest motorable villages and Langza's giant Buddha statue above the fossil-rich plateau.", type: "sightseeing" },
          { _key: "d3", title: "Kibber and Ki Monastery", description: "Pass snow-leopard country at Kibber and visit the 1,000-year-old fortress monastery with panoramic views.", location: { name: "Ki Monastery", lat: 32.319, lng: 78.024 }, type: "sightseeing" },
          { _key: "d4", title: "Overnight at Sakya Homestay, Kaza", description: "Return to Kaza after the ~80 km loop.", type: "accommodation" },
        ],
      },
      {
        _key: "day5",
        dayNumber: 5,
        title: "Kaza → Pin Valley → Mud Village",
        date: "2026-10-03",
        summary: "A short but rugged drive into Pin Valley National Park and the remote village of Mud.",
        activities: [
          { _key: "e1", title: "Drive to Mud Village (~50 km)", description: "Take the rough track through Pin Valley; drive carefully at stream crossings.", type: "transport" },
          { _key: "e2", title: "Pin Valley National Park", description: "Explore snow-leopard and Siberian ibex habitat.", type: "sightseeing" },
          { _key: "e3", title: "Overnight at a Mud Village homestay", description: "Arrange it from Kaza before departure.", notes: "There is zero mobile network. Inform someone of the day plan and carry extra water, food, and warm clothing.", type: "accommodation" },
        ],
      },
      {
        _key: "day6",
        dayNumber: 6,
        title: "Pin Valley → Dhankar → Tabo",
        date: "2026-10-04",
        summary: "Cliff monasteries, a high-altitude lake hike, and a millennium of Buddhist art.",
        activities: [
          { _key: "f1", title: "Drive to Dhankar and Tabo (~100 km)", type: "transport" },
          { _key: "f2", title: "Dhankar Monastery and Lake", description: "See the clifftop monastery above the Spiti-Pin confluence and allow 2–3 hours round trip for the lake hike.", type: "sightseeing" },
          { _key: "f3", title: "Tabo Monastery", description: "Visit India's oldest continuously operating monastery (996 AD) and its cave frescoes.", location: { name: "Tabo Monastery", lat: 32.095, lng: 78.384 }, type: "sightseeing" },
          { _key: "f4", title: "Overnight at Namsay Homestay, Tabo", type: "accommodation" },
        ],
      },
      {
        _key: "day7",
        dayNumber: 7,
        title: "Tabo → Nako → Gue → Kalpa",
        date: "2026-10-05",
        summary: "Lakes, a centuries-old mummy stupa, and Kinner Kailash in alpenglow.",
        activities: [
          { _key: "g1", title: "Drive to Kalpa via Nako and Gue (~150–190 km)", type: "transport" },
          { _key: "g2", title: "Nako Lake and Gue Mummy Stupa", description: "See the high-altitude lake with its island monastery and the naturally mummified Buddhist monk.", type: "sightseeing" },
          { _key: "g3", title: "Kalpa sunset", description: "Refuel at Reckong Peo or Tapri, then watch Kinner Kailash (6,050 m) glow at sunset.", location: { name: "Kalpa, Kinnaur", lat: 31.539, lng: 78.263 }, type: "sightseeing" },
          { _key: "g4", title: "Overnight at Akshit Homestay, Kalpa", type: "accommodation" },
        ],
      },
      {
        _key: "day8",
        dayNumber: 8,
        title: "Kalpa → Roghi Village → Chitkul",
        date: "2026-10-06",
        summary: "Follow the Baspa Valley to India's last inhabited village near the Indo-Tibetan border.",
        activities: [
          { _key: "h1", title: "Drive to Chitkul via Roghi (~65 km)", description: "Stop at Roghi's hanging bridge and apple orchards.", type: "transport" },
          { _key: "h2", title: "Chitkul and Baspa River", description: "Explore the last inhabited border village and its crystal-clear glacial river.", location: { name: "Chitkul, Kinnaur", lat: 31.351, lng: 78.438 }, type: "sightseeing" },
          { _key: "h3", title: "Overnight at RR Homestay, Chitkul", notes: "Foreign nationals should check current border-area permit requirements.", type: "accommodation" },
        ],
      },
      {
        _key: "day9",
        dayNumber: 9,
        title: "Chitkul → Sangla → Narkanda",
        date: "2026-10-07",
        summary: "Leave the cold desert behind for Sangla's greenery, the Sutlej gorge, and Hatu Peak.",
        activities: [
          { _key: "i1", title: "Drive to Narkanda via Sangla (~160–200 km)", description: "Follow the dramatic Sutlej river gorge through Kinnaur.", type: "transport" },
          { _key: "i2", title: "Sangla Valley and Hatu Peak", description: "Enjoy the lush valley contrast and 360° Himalayan views from accessible Hatu Peak near Narkanda.", location: { name: "Hatu Peak, Narkanda", lat: 31.272, lng: 77.502 }, type: "sightseeing" },
          { _key: "i3", title: "Overnight at Hatu Valley Homestay, Narkanda", type: "accommodation" },
        ],
      },
      {
        _key: "day10",
        dayNumber: 10,
        title: "Narkanda → Shimla → Chandigarh → New Delhi",
        date: "2026-10-08",
        summary: "The all-weather homeward run, descending through Shimla and the plains to Delhi.",
        activities: [
          { _key: "j1", title: "Drive home (~350–400 km)", description: "Have breakfast in Shimla, follow NH-5 to Chandigarh, and stop for lunch in Chandigarh or Ambala.", type: "transport" },
          { _key: "j2", title: "Arrive in New Delhi", description: "Aim for an evening arrival after 10 days and more than 1,800 km.", location: { name: "New Delhi", lat: 28.614, lng: 77.209 }, type: "activity" },
        ],
      },
    ],
  },
  {
    _id: "trip-mysore-coorg-wayanad-ooty",
    title: "Mysore, Coorg, Wayanad, Ooty & Coonoor Road Trip",
    slug: "mysore-coorg-wayanad-ooty",
    excerpt:
      "A scenic South India circuit from Pune through Mysore, Coorg, Wayanad, Ooty, and Coonoor—palaces, safaris, coffee country, caves, and the Nilgiris.",
    tags: ["Road Trip", "India", "South India", "Karnataka", "Kerala", "Mysore", "Ooty", "Coorg", "Culture", "Food", "Mountains", "Nature"],
    country: "India",
    bestSuggestedMonth: "October – March",
    status: "published",
    viewCount: 0,
    currency: "INR",
    tripType: "Road Trip",
    readingTime: 10,
    _createdAt: "2026-08-24T00:00:00Z",
    _updatedAt: "2026-08-24T00:00:00Z",
    coverImage: undefined,
    itinerary: [
      {
        _key: "south-day1",
        dayNumber: 1,
        title: "Pune → Mysore",
        summary: "Start the circuit with the long Pune-to-Mysore drive, approximately 850 km on the route map.",
        activities: [
          { _key: "s1a", title: "Drive from Pune to Mysore (~850 km)", description: "Begin early and plan the drive around rest and meal breaks.", type: "transport" },
          { _key: "s1b", title: "Fuel stop at Hubli", description: "One of the route map's listed fuel stops—top up before continuing south.", type: "activity" },
          { _key: "s1c", title: "Mysore Palace", description: "Make Mysore Palace the headline stop on arrival.", type: "sightseeing" },
          { _key: "s1d", title: "Overnight in Mysore", description: "Rest before the shorter Coorg leg.", type: "accommodation" },
        ],
      },
      {
        _key: "south-day2",
        dayNumber: 2,
        title: "Mysore → Coorg",
        summary: "A roughly 120 km transition from Mysore to Coorg, with wildlife and coffee-country highlights.",
        activities: [
          { _key: "s2a", title: "Drive from Mysore to Coorg (~120 km)", type: "transport" },
          { _key: "s2b", title: "Bandipur Safari", description: "Plan a safari stop as featured on the route map.", type: "sightseeing" },
          { _key: "s2c", title: "Fuel stop at Gonikoppal", description: "Top up at the listed fuel stop before settling into Coorg.", type: "activity" },
          { _key: "s2d", title: "Overnight in Coorg", type: "accommodation" },
        ],
      },
      {
        _key: "south-day3",
        dayNumber: 3,
        title: "Explore Coorg",
        summary: "Spend a slower day among Coorg's waterfalls, coffee plantations, and cultural landmarks.",
        activities: [
          { _key: "s3a", title: "Abbey Falls", description: "Visit the waterfall highlighted on the route map.", type: "sightseeing" },
          { _key: "s3b", title: "Coffee plantations", description: "Explore one of the route map's featured hidden gems.", type: "activity" },
          { _key: "s3c", title: "Golden Temple", description: "Include the Golden Temple, listed among the hidden gems.", type: "sightseeing" },
          { _key: "s3d", title: "Second night in Coorg", type: "accommodation" },
        ],
      },
      {
        _key: "south-day4",
        dayNumber: 4,
        title: "Coorg → Wayanad",
        summary: "Continue into Kerala on the approximately 130 km Coorg-to-Wayanad leg.",
        activities: [
          { _key: "s4a", title: "Drive from Coorg to Wayanad (~130 km)", type: "transport" },
          { _key: "s4b", title: "Fuel stop at Gundlupet", description: "Refuel at one of the listed stops along the route.", type: "activity" },
          { _key: "s4c", title: "Edakkal Caves", description: "Explore the cave complex featured on the route map.", type: "sightseeing" },
          { _key: "s4d", title: "Overnight in Wayanad", type: "accommodation" },
        ],
      },
      {
        _key: "south-day5",
        dayNumber: 5,
        title: "Wayanad → Ooty",
        summary: "Climb from Wayanad into the Nilgiris on the approximately 110 km Wayanad-to-Ooty route.",
        activities: [
          { _key: "s5a", title: "Drive from Wayanad to Ooty (~110 km)", type: "transport" },
          { _key: "s5b", title: "Ooty Lake", description: "Enjoy the lakeside stop shown among the route highlights.", type: "sightseeing" },
          { _key: "s5c", title: "Overnight in Ooty", notes: "Carry light woollens and rain gear, as recommended on the route map.", type: "accommodation" },
        ],
      },
      {
        _key: "south-day6",
        dayNumber: 6,
        title: "Ooty → Coonoor",
        summary: "A relaxed Nilgiris day, centred on Coonoor and Toda culture.",
        activities: [
          { _key: "s6a", title: "Drive from Ooty to Coonoor", description: "Continue south from Ooty to Coonoor on the mapped circuit.", type: "transport" },
          { _key: "s6b", title: "Toda Village", description: "Visit the Toda Village featured as a hidden gem.", type: "sightseeing" },
          { _key: "s6c", title: "Overnight in Coonoor", notes: "Pack snacks and essential medicines for the road, as noted on the route map.", type: "accommodation" },
        ],
      },
      {
        _key: "south-day7",
        dayNumber: 7,
        title: "Coonoor → Pune",
        summary: "Complete the return leg from Coonoor to Pune; the image does not specify a distance for this final route.",
        activities: [
          { _key: "s7a", title: "Begin the return drive to Pune", description: "Plan breaks around the long homeward journey.", type: "transport" },
          { _key: "s7b", title: "Fuel stop at Salem", description: "Use the final listed fuel stop to prepare for the return route.", type: "activity" },
          { _key: "s7c", title: "Arrive in Pune", description: "Finish the Mysore–Coorg–Wayanad–Ooty–Coonoor circuit.", type: "activity" },
        ],
      },
    ],
  },
  {
    _id: "trip-rajasthan",
    title: "Rajasthan — The Desert Kingdom",
    slug: "rajasthan-desert-kingdom",
    excerpt:
      "Forts, palaces, camel dunes, and the most vivid colors you'll ever see — a royal journey through India's legendary desert state.",
    tags: ["Culture", "Heritage", "Rajasthan", "India", "Desert"],
    country: "India",
    startDate: "2023-11-10",
    endDate: "2023-11-19",
    bestSuggestedMonth: "October – March",
    status: "published",
    viewCount: 2156,
    totalBudget: 35000,
    currency: "INR",
    tripType: "Cultural",
    readingTime: 10,
    _createdAt: "2023-12-01T00:00:00Z",
    _updatedAt: "2023-12-01T00:00:00Z",
    coverImage: undefined,
    itinerary: [
      {
        _key: "rajasthan-day1",
        dayNumber: 1,
        title: "Arrive in Jaipur → Pink City Evening",
        date: "2023-11-10",
        summary: "Begin in Jaipur with an easy first day in the historic centre and a sunset introduction to the Pink City.",
        activities: [
          { _key: "r1a", title: "Arrive and check in at Jaipur", description: "Keep arrival day flexible and arrange local transport for the city circuit.", location: { name: "Jaipur", lat: 26.9124, lng: 75.7873 }, type: "accommodation" },
          { _key: "r1b", title: "Hawa Mahal and Bapu Bazaar", description: "See the iconic façade, then browse the old-city lanes and handicraft markets.", location: { name: "Hawa Mahal", lat: 26.9239, lng: 75.8267 }, type: "sightseeing" },
          { _key: "r1c", title: "Sunset at Nahargarh Fort", description: "Take in a wide view of Jaipur as the city lights come on.", location: { name: "Nahargarh Fort", lat: 26.9373, lng: 75.815 }, type: "sightseeing" },
          { _key: "r1d", title: "Overnight in Jaipur", notes: "Use licensed guides and agree taxi or auto fares before setting off.", type: "accommodation" },
        ],
      },
      {
        _key: "rajasthan-day2",
        dayNumber: 2,
        title: "Amer → Jaigarh → Jaipur Heritage Core",
        date: "2023-11-11",
        summary: "Dedicate a full day to Jaipur's hill forts, royal collections, and astronomical heritage.",
        activities: [
          { _key: "r2a", title: "Amer Fort", description: "Start early to explore the palace complex before the busiest period.", location: { name: "Amer Fort", lat: 26.9855, lng: 75.8513 }, type: "sightseeing" },
          { _key: "r2b", title: "Jaigarh Fort", description: "Continue to the hilltop fort for ramparts and views across Amer.", location: { name: "Jaigarh Fort", lat: 26.9855, lng: 75.8453 }, type: "sightseeing" },
          { _key: "r2c", title: "City Palace and Jantar Mantar", description: "Return to central Jaipur for royal collections and the historic observatory.", location: { name: "City Palace, Jaipur", lat: 26.9258, lng: 75.8237 }, type: "sightseeing" },
          { _key: "r2d", title: "Jaipur food walk", description: "Finish with Rajasthani specialities in the old city.", type: "food" },
        ],
      },
      {
        _key: "rajasthan-day3",
        dayNumber: 3,
        title: "Jaipur → Bikaner",
        date: "2023-11-12",
        summary: "Head into the desert state via Bikaner, known for its imposing fort and old-city character.",
        activities: [
          { _key: "r3a", title: "Drive from Jaipur to Bikaner", description: "Leave after breakfast and keep a buffer for highway stops and check-in.", type: "transport" },
          { _key: "r3b", title: "Junagarh Fort", description: "Explore Bikaner's richly decorated fort complex in the afternoon.", location: { name: "Junagarh Fort, Bikaner", lat: 28.0229, lng: 73.3178 }, type: "sightseeing" },
          { _key: "r3c", title: "Old Bikaner evening", description: "Walk the old-city lanes and sample local snacks.", type: "food" },
          { _key: "r3d", title: "Overnight in Bikaner", type: "accommodation" },
        ],
      },
      {
        _key: "rajasthan-day4",
        dayNumber: 4,
        title: "Bikaner → Jaisalmer",
        date: "2023-11-13",
        summary: "Travel west into the Thar Desert and arrive in the Golden City.",
        activities: [
          { _key: "r4a", title: "Drive from Bikaner to Jaisalmer", description: "Carry water and snacks for the long desert-road day.", type: "transport" },
          { _key: "r4b", title: "Gadisar Lake at sunset", description: "Take a gentle first look at Jaisalmer around the historic reservoir.", location: { name: "Gadisar Lake", lat: 26.912, lng: 70.9229 }, type: "sightseeing" },
          { _key: "r4c", title: "Overnight in Jaisalmer", description: "Rest before a full day inside the fort and old city.", type: "accommodation" },
        ],
      },
      {
        _key: "rajasthan-day5",
        dayNumber: 5,
        title: "Jaisalmer Fort → Havelis → Bada Bagh",
        date: "2023-11-14",
        summary: "Explore the living fort, intricate merchant homes, and desert-era cenotaphs.",
        activities: [
          { _key: "r5a", title: "Jaisalmer Fort", description: "Walk the living fort's lanes, temples, and viewpoints early in the day.", location: { name: "Jaisalmer Fort", lat: 26.9123, lng: 70.912 }, type: "sightseeing" },
          { _key: "r5b", title: "Patwon Ki Haveli and Salim Singh Ki Haveli", description: "See Jaisalmer's finely carved merchant architecture.", location: { name: "Patwon Ki Haveli", lat: 26.9157, lng: 70.9083 }, type: "sightseeing" },
          { _key: "r5c", title: "Bada Bagh sunset", description: "Visit the cenotaph complex outside the city as the sandstone turns gold.", location: { name: "Bada Bagh", lat: 26.9628, lng: 70.8708 }, type: "sightseeing" },
          { _key: "r5d", title: "Second night in Jaisalmer", type: "accommodation" },
        ],
      },
      {
        _key: "rajasthan-day6",
        dayNumber: 6,
        title: "Jaisalmer → Kuldhara → Sam Sand Dunes",
        date: "2023-11-15",
        summary: "Move from the city into the desert for a dunes sunset and overnight camp experience.",
        activities: [
          { _key: "r6a", title: "Kuldhara village", description: "Stop at the abandoned village on the route toward the dunes.", location: { name: "Kuldhara", lat: 26.9202, lng: 70.713 }, type: "sightseeing" },
          { _key: "r6b", title: "Drive to Sam Sand Dunes", description: "Continue west to the dunes; carry a light layer for the cooler desert evening.", location: { name: "Sam Sand Dunes", lat: 26.8144, lng: 70.5163 }, type: "transport" },
          { _key: "r6c", title: "Desert sunset and cultural programme", description: "Enjoy the dunes at sunset and an evening of local music and food at camp.", type: "activity" },
          { _key: "r6d", title: "Overnight desert camp", notes: "Choose a licensed camp operator and avoid driving on dunes outside designated routes.", type: "accommodation" },
        ],
      },
      {
        _key: "rajasthan-day7",
        dayNumber: 7,
        title: "Jaisalmer → Jodhpur",
        date: "2023-11-16",
        summary: "Leave the Thar behind and reach the Blue City for a relaxed evening around its clock tower market.",
        activities: [
          { _key: "r7a", title: "Drive from Jaisalmer to Jodhpur", description: "Start after breakfast and plan a late-afternoon check-in.", type: "transport" },
          { _key: "r7b", title: "Clock Tower and Sardar Market", description: "Walk the market area for spices, textiles, and a first taste of Jodhpur.", location: { name: "Ghanta Ghar, Jodhpur", lat: 26.292, lng: 73.0246 }, type: "sightseeing" },
          { _key: "r7c", title: "Overnight in Jodhpur", type: "accommodation" },
        ],
      },
      {
        _key: "rajasthan-day8",
        dayNumber: 8,
        title: "Mehrangarh → Jaswant Thada → Mandore",
        date: "2023-11-17",
        summary: "A full Jodhpur day around its great hill fort, memorial architecture, and gardens.",
        activities: [
          { _key: "r8a", title: "Mehrangarh Fort", description: "Give Rajasthan's great hill fort the morning for galleries, ramparts, and city views.", location: { name: "Mehrangarh Fort", lat: 26.298, lng: 73.0181 }, type: "sightseeing" },
          { _key: "r8b", title: "Jaswant Thada", description: "Visit the marble memorial immediately below the fort.", location: { name: "Jaswant Thada", lat: 26.3031, lng: 73.0205 }, type: "sightseeing" },
          { _key: "r8c", title: "Mandore Gardens", description: "Spend the later afternoon among the historic cenotaphs and gardens.", location: { name: "Mandore Gardens", lat: 26.3545, lng: 73.0394 }, type: "sightseeing" },
          { _key: "r8d", title: "Second night in Jodhpur", type: "accommodation" },
        ],
      },
      {
        _key: "rajasthan-day9",
        dayNumber: 9,
        title: "Jodhpur → Ranakpur → Udaipur",
        date: "2023-11-18",
        summary: "Cross the Aravallis via Ranakpur's celebrated Jain temple complex to the City of Lakes.",
        activities: [
          { _key: "r9a", title: "Drive to Ranakpur", description: "Leave early for the temple stop and the scenic Aravalli approach.", type: "transport" },
          { _key: "r9b", title: "Ranakpur Jain Temple", description: "Explore the celebrated marble temple complex with its carved columns.", location: { name: "Ranakpur Jain Temple", lat: 25.1165, lng: 73.4729 }, type: "sightseeing" },
          { _key: "r9c", title: "Continue to Udaipur", description: "Check in and head to the lakefront for an evening walk.", location: { name: "Udaipur", lat: 24.5854, lng: 73.7125 }, type: "transport" },
          { _key: "r9d", title: "Lake Pichola sunset", description: "Take in the waterfront views at the end of the road day.", type: "sightseeing" },
        ],
      },
      {
        _key: "rajasthan-day10",
        dayNumber: 10,
        title: "Udaipur City Palace → Lake Pichola → Departure",
        date: "2023-11-19",
        summary: "End in Udaipur with lakeside palaces, gardens, and a measured departure buffer.",
        activities: [
          { _key: "r10a", title: "City Palace and Jagdish Temple", description: "Start at Udaipur's palace complex, then walk to the nearby temple and old-city lanes.", location: { name: "City Palace, Udaipur", lat: 24.5764, lng: 73.6835 }, type: "sightseeing" },
          { _key: "r10b", title: "Saheliyon-ki-Bari", description: "Visit the historic garden before the final lakefront stop.", location: { name: "Saheliyon-ki-Bari", lat: 24.602, lng: 73.6878 }, type: "sightseeing" },
          { _key: "r10c", title: "Lake Pichola boat ride", description: "If timing permits, finish with a lake ride and views of the palace skyline.", location: { name: "Lake Pichola", lat: 24.5713, lng: 73.6791 }, type: "activity" },
          { _key: "r10d", title: "Depart Udaipur", notes: "Keep sufficient transfer time for the airport or railway station and reconfirm transport the night before.", type: "transport" },
        ],
      },
    ],
  },
  {
    _id: "trip-goa",
    title: "Goa — Beyond the Beach Shacks",
    slug: "goa-beyond-beaches",
    excerpt:
      "Old Goa churches, hidden spice farms, Portuguese-era homes, and yes — a few perfect sunsets over the Arabian Sea.",
    tags: ["Beach", "Food", "Coastal", "Goa", "India"],
    country: "India",
    startDate: "2023-01-05",
    endDate: "2023-01-11",
    bestSuggestedMonth: "November – February",
    status: "published",
    viewCount: 987,
    totalBudget: 18000,
    currency: "INR",
    tripType: "Leisure",
    readingTime: 7,
    _createdAt: "2023-02-01T00:00:00Z",
    _updatedAt: "2023-02-01T00:00:00Z",
    coverImage: undefined,
    itinerary: [
      {
        _key: "goa-day1",
        dayNumber: 1,
        title: "Arrive in Panaji → Fontainhas → Miramar",
        date: "2023-01-05",
        summary: "Ease into Goa through Panaji's Latin Quarter, with a sunset finish on the Mandovi waterfront.",
        activities: [
          { _key: "g1a", title: "Arrive and check in at Panaji", description: "Settle in, collect a local SIM if needed, and keep the first day unhurried.", location: { name: "Panaji", lat: 15.4909, lng: 73.8278 }, type: "accommodation" },
          { _key: "g1b", title: "Walk through Fontainhas", description: "Explore Panaji's Portuguese-era Latin Quarter, its colourful homes, lanes, and cafés.", location: { name: "Fontainhas, Panaji", lat: 15.4984, lng: 73.8281 }, type: "sightseeing" },
          { _key: "g1c", title: "Sunset at Miramar Beach", description: "End the day by the Arabian Sea near the Mandovi estuary.", location: { name: "Miramar Beach", lat: 15.4798, lng: 73.8078 }, type: "sightseeing" },
          { _key: "g1d", title: "Dinner in Panaji", description: "Try a Goan meal and confirm the following day's Old Goa transport plan.", type: "food" },
        ],
      },
      {
        _key: "goa-day2",
        dayNumber: 2,
        title: "Panaji → Old Goa → Divar Island",
        date: "2023-01-06",
        summary: "A heritage-focused day among Old Goa's churches, followed by a quieter island detour.",
        activities: [
          { _key: "g2a", title: "Explore Old Goa", description: "Start early to comfortably explore the historic church precinct before the busiest hours.", location: { name: "Old Goa", lat: 15.5009, lng: 73.9116 }, type: "sightseeing" },
          { _key: "g2b", title: "Basilica of Bom Jesus", description: "Visit one of Goa's best-known Portuguese-era churches.", location: { name: "Basilica of Bom Jesus", lat: 15.5007, lng: 73.9114 }, type: "sightseeing" },
          { _key: "g2c", title: "Ferry to Divar Island", description: "Take the short ferry for village lanes, fields, and a slower side of the region.", location: { name: "Divar Island", lat: 15.5266, lng: 73.8745 }, type: "activity" },
          { _key: "g2d", title: "Second night in Panaji", notes: "Carry water and sun protection; heritage sites involve a fair amount of walking.", type: "accommodation" },
        ],
      },
      {
        _key: "goa-day3",
        dayNumber: 3,
        title: "Panaji → Candolim → Anjuna → Vagator",
        date: "2023-01-07",
        summary: "Head north for Goa's classic coastal landmarks, beach time, and a cliffside sunset.",
        activities: [
          { _key: "g3a", title: "Drive to North Goa", description: "Move north from Panaji, allowing time for traffic and parking around the popular beach belt.", type: "transport" },
          { _key: "g3b", title: "Fort Aguada and Candolim Beach", description: "Pair the hilltop fort views with a relaxed beach stop.", location: { name: "Fort Aguada", lat: 15.4921, lng: 73.7738 }, type: "sightseeing" },
          { _key: "g3c", title: "Anjuna Beach", description: "Explore the beach and nearby cafés at an unhurried pace.", location: { name: "Anjuna Beach", lat: 15.573, lng: 73.7407 }, type: "sightseeing" },
          { _key: "g3d", title: "Sunset at Vagator", description: "Finish with views from the Vagator cliffside.", location: { name: "Vagator Beach", lat: 15.5977, lng: 73.7338 }, type: "sightseeing" },
          { _key: "g3e", title: "Overnight in North Goa", type: "accommodation" },
        ],
      },
      {
        _key: "goa-day4",
        dayNumber: 4,
        title: "Mandrem → Arambol → Chapora",
        date: "2023-01-08",
        summary: "A quieter North Goa loop of broad beaches, a village atmosphere, and fort views.",
        activities: [
          { _key: "g4a", title: "Morning at Mandrem Beach", description: "Start early for a quieter stretch of sand and an easy breakfast.", location: { name: "Mandrem Beach", lat: 15.6571, lng: 73.7101 }, type: "sightseeing" },
          { _key: "g4b", title: "Explore Arambol", description: "Spend the afternoon around Arambol's beach and local lanes.", location: { name: "Arambol Beach", lat: 15.6863, lng: 73.7045 }, type: "sightseeing" },
          { _key: "g4c", title: "Chapora Fort at golden hour", description: "Climb to the fort for wide coastal views before sunset.", location: { name: "Chapora Fort", lat: 15.6066, lng: 73.7392 }, type: "sightseeing" },
          { _key: "g4d", title: "Second night in North Goa", notes: "Use a cab or designated driver if you plan to drink; do not ride or drive after alcohol.", type: "accommodation" },
        ],
      },
      {
        _key: "goa-day5",
        dayNumber: 5,
        title: "North Goa → Ponda → Palolem",
        date: "2023-01-09",
        summary: "Cross Goa through its green interior, stopping at a spice plantation before reaching the slower South Goa coast.",
        activities: [
          { _key: "g5a", title: "Drive to Ponda", description: "Leave North Goa after breakfast and travel inland toward Ponda.", type: "transport" },
          { _key: "g5b", title: "Goan spice plantation visit", description: "Take a guided plantation walk and learn about the region's spice-growing traditions.", location: { name: "Ponda", lat: 15.403, lng: 74.015 }, type: "activity" },
          { _key: "g5c", title: "Continue to Palolem", description: "Head south to Palolem and check in near the beach.", location: { name: "Palolem Beach", lat: 15.01, lng: 74.023 }, type: "transport" },
          { _key: "g5d", title: "Palolem sunset and overnight", description: "Keep the evening open for the beach and a relaxed dinner.", type: "accommodation" },
        ],
      },
      {
        _key: "goa-day6",
        dayNumber: 6,
        title: "Palolem → Agonda → Cola Beach",
        date: "2023-01-10",
        summary: "A South Goa beach day built around quieter coves and a low-key coastal pace.",
        activities: [
          { _key: "g6a", title: "Morning at Palolem", description: "Enjoy the beach before moving on to the quieter southern coves.", type: "sightseeing" },
          { _key: "g6b", title: "Agonda Beach", description: "Spend time at the long, less-built-up beach south of Palolem.", location: { name: "Agonda Beach", lat: 15.0466, lng: 73.9868 }, type: "sightseeing" },
          { _key: "g6c", title: "Cola Beach", description: "Visit the secluded beach and lagoon area, allowing for slower local roads.", location: { name: "Cola Beach", lat: 15.0876, lng: 73.9889 }, type: "sightseeing" },
          { _key: "g6d", title: "Second night in South Goa", notes: "Keep swim plans conservative: respect flags, currents, weather, and local advice.", type: "accommodation" },
        ],
      },
      {
        _key: "goa-day7",
        dayNumber: 7,
        title: "South Goa → Margao → Departure",
        date: "2023-01-11",
        summary: "Wrap up with a final local stop and leave a sensible buffer for the airport or railway station.",
        activities: [
          { _key: "g7a", title: "Breakfast and check-out in South Goa", description: "Pack up early and keep valuables, documents, and chargers together for departure.", type: "accommodation" },
          { _key: "g7b", title: "Stop in Margao", description: "Use Margao for a final meal or quick shopping before continuing to your departure point.", location: { name: "Margao", lat: 15.2832, lng: 73.9862 }, type: "food" },
          { _key: "g7c", title: "Depart Goa", description: "Allow a comfortable buffer for traffic and transfer time.", type: "transport" },
        ],
      },
    ],
  },
  // ─── 6 NEW TRIPS ───────────────────────────────────────────────────────────
  {
    _id: "trip-sikkim-7-days",
    title: "7 Days in Sikkim — Gurudongmar, Yumthang & Pelling",
    slug: "sikkim-7-days",
    excerpt:
      "North Sikkim's sacred high-altitude lake at 5,183 m, the 'Valley of Flowers' at Yumthang, Zero Point snow fields, and Kanchenjunga views from Pelling — a complete week across Sikkim.",
    tags: ["Northeast", "Sikkim", "Mountains", "Adventure", "Trekking", "Culture", "India", "High Altitude"],
    country: "India",
    bestSuggestedMonth: "March – June & September – December",
    status: "published",
    viewCount: 643,
    totalBudget: 27000,
    currency: "INR",
    tripType: "Mountain/Nature",
    readingTime: 12,
    _createdAt: "2026-08-26T00:00:00Z",
    _updatedAt: "2026-08-26T00:00:00Z",
    coverImage: undefined,
    itinerary: [
      {
        _key: "sk-day1",
        dayNumber: 1,
        title: "Bagdogra / NJP → Gangtok",
        date: undefined,
        summary: "Transfer from Bagdogra Airport or NJP railway station to Gangtok through the scenic Teesta valley, arriving in time for an evening stroll on MG Marg.",
        activities: [
          { _key: "sk1a", title: "Land at Bagdogra / arrive NJP", description: "Private cab pickup, drive to Gangtok (~4–5 hrs, 125 km) through the Teesta river valley.", location: { name: "Bagdogra Airport, Siliguri", lat: 26.6812, lng: 88.3286 }, type: "transport" },
          { _key: "sk1b", title: "Lunch stop at Rangpo / Melli", description: "Riverside dhaba lunch en route — Sikkim border crossing.", type: "food" },
          { _key: "sk1c", title: "Check-in at Gangtok hotel", description: "Arrange Inner Line Permit (ILP) with hotel/agent. Keep 4 passport photos and ID proof handy.", location: { name: "Gangtok", lat: 27.3389, lng: 88.6065 }, type: "accommodation" },
          { _key: "sk1d", title: "Evening stroll at MG Marg", description: "Gangtok's pedestrian-only promenade — cafés, handicraft shops, and mountain views.", type: "activity" },
          { _key: "sk1e", title: "Dinner at Tibetan/Sikkimese restaurant", description: "Try Thukpa, momos, or traditional Sikkimese pork dishes.", type: "food" },
        ],
      },
      {
        _key: "sk-day2",
        dayNumber: 2,
        title: "Gangtok Local Sightseeing",
        date: undefined,
        summary: "Rumtek Monastery — the largest in Sikkim — red pandas at the Himalayan Zoological Park, Ganesh Tok, and Kanchenjunga views from Tashi viewpoint.",
        activities: [
          { _key: "sk2a", title: "Rumtek Monastery", description: "Largest monastery in Sikkim (~24 km from Gangtok). Closed on Mondays.", location: { name: "Rumtek Monastery", lat: 27.2854, lng: 88.5613 }, type: "sightseeing" },
          { _key: "sk2b", title: "Ganesh Tok & Hanuman Tok viewpoints", description: "Hilltop viewpoints offering panoramic Himalayan vistas above Gangtok.", type: "sightseeing" },
          { _key: "sk2c", title: "Himalayan Zoological Park", description: "Home to red pandas, snow leopards, and Himalayan wolves. Closed Mondays.", type: "activity" },
          { _key: "sk2d", title: "Tashi View Point", description: "Best viewpoint for Kanchenjunga (8,586 m) — visit early morning for clearest mountain visibility.", location: { name: "Tashi Viewpoint, Gangtok", lat: 27.3633, lng: 88.5958 }, type: "sightseeing" },
          { _key: "sk2e", title: "Evening shopping at Lal Bazaar", description: "Gangtok's main market for handicrafts, Tibetan souvenirs, and local produce.", type: "activity" },
        ],
      },
      {
        _key: "sk-day3",
        dayNumber: 3,
        title: "Gangtok → Lachen (North Sikkim)",
        date: undefined,
        summary: "Enter restricted North Sikkim on a permit-cleared vehicle, stopping at Naga and Seven Sisters Falls before arriving at Lachen to acclimatize at 2,750 m.",
        activities: [
          { _key: "sk3a", title: "Depart Gangtok in permit vehicle", description: "North Sikkim Protected Area Permit required — arrange via registered travel agent.", type: "transport" },
          { _key: "sk3b", title: "Naga Waterfall & Seven Sisters Falls", description: "Series of seven cascading waterfalls along the North Sikkim highway.", location: { name: "Seven Sisters Falls, North Sikkim", lat: 27.5000, lng: 88.6000 }, type: "sightseeing" },
          { _key: "sk3c", title: "Lunch at Chungthang", description: "Confluence town of Lachen Chu and Lachung Chu rivers — last major market.", type: "food" },
          { _key: "sk3d", title: "Arrive Lachen, acclimatize", description: "Check-in at homestay (~2,750 m). Minimal network — BSNL works best. Carry warm layers.", location: { name: "Lachen", lat: 27.7167, lng: 88.55 }, type: "accommodation" },
        ],
      },
      {
        _key: "sk-day4",
        dayNumber: 4,
        title: "Gurudongmar Lake → Lachung",
        date: undefined,
        summary: "A 4:30 AM departure for sacred Gurudongmar Lake at 5,183 m — one of the highest lakes in the world — then drive across to Lachung for the night.",
        activities: [
          { _key: "sk4a", title: "Early departure for Gurudongmar Lake", description: "Leave at 4:30 AM for the ~3 hr drive. High-altitude sickness risk — move slowly, stay hydrated.", type: "transport" },
          { _key: "sk4b", title: "Gurudongmar Lake", description: "Sacred Buddhist and Sikh lake at 5,183 m. Photography, prayer-flag walk. Partially frozen year-round.", location: { name: "Gurudongmar Lake", lat: 28.0333, lng: 88.7 }, type: "sightseeing" },
          { _key: "sk4c", title: "Return to Lachen, breakfast", description: "Descend to Lachen for a late breakfast and recovery before the drive to Lachung.", type: "food" },
          { _key: "sk4d", title: "Drive Lachen → Lachung", description: "Scenic 3–4 hr drive through North Sikkim's river valleys.", type: "transport" },
          { _key: "sk4e", title: "Lachung Monastery & check-in", description: "Explore the peaceful monastery in Lachung before settling in for the night.", location: { name: "Lachung", lat: 27.6913, lng: 88.7419 }, type: "accommodation" },
        ],
      },
      {
        _key: "sk-day5",
        dayNumber: 5,
        title: "Yumthang Valley & Zero Point → Gangtok",
        date: undefined,
        summary: "The 'Valley of Flowers' at Yumthang with rhododendron meadows and hot springs, then Zero Point snow fields at 4,600 m — followed by the long drive back to Gangtok.",
        activities: [
          { _key: "sk5a", title: "Yumthang Valley", description: "Valley of Flowers — rhododendron bloom Mar–May, hot springs nearby. Altitude ~3,564 m.", location: { name: "Yumthang Valley", lat: 27.8167, lng: 88.6833 }, type: "sightseeing" },
          { _key: "sk5b", title: "Zero Point (Snow Point)", description: "~4,600 m — weather-dependent snow fields. Rent snow boots locally (~₹150). Backup plan required if road is closed.", type: "sightseeing" },
          { _key: "sk5c", title: "Return to Lachung, lunch", description: "Lunch before the long drive south.", type: "food" },
          { _key: "sk5d", title: "Long drive back to Gangtok", description: "~5–6 hour drive. Check-in and dinner in Gangtok.", location: { name: "Gangtok", lat: 27.3389, lng: 88.6065 }, type: "accommodation" },
        ],
      },
      {
        _key: "sk-day6",
        dayNumber: 6,
        title: "Gangtok → Pelling (via Ravangla)",
        date: undefined,
        summary: "Drive to West Sikkim via Ravangla, stopping at the giant Buddha Park and Ralang Monastery, arriving in Pelling for sunset views of the Kanchenjunga massif.",
        activities: [
          { _key: "sk6a", title: "Drive to Ravangla", description: "Scenic 2 hr drive south through South Sikkim. Alternative route via Namchi covers Char Dham replica if time allows.", type: "transport" },
          { _key: "sk6b", title: "Buddha Park & Ralang Monastery, Ravangla", description: "One of Sikkim's most striking hilltop Buddha statues with valley views.", location: { name: "Ravangla", lat: 27.3167, lng: 88.3667 }, type: "sightseeing" },
          { _key: "sk6c", title: "Continue to Pelling", description: "Check-in, then watch the Kanchenjunga massif at sunset from the hotel viewpoint.", location: { name: "Pelling", lat: 27.2167, lng: 88.2167 }, type: "accommodation" },
        ],
      },
      {
        _key: "sk-day7",
        dayNumber: 7,
        title: "Pelling Sightseeing & Departure",
        date: undefined,
        summary: "Sunrise from Pelling Skywalk, Pemayangtse Monastery — one of the oldest in Sikkim — Rabdentse Ruins, then depart for Bagdogra/NJP.",
        activities: [
          { _key: "sk7a", title: "Sunrise at Pelling Skywalk / Sangey viewpoint", description: "Kanchenjunga at dawn — one of the finest mountain views in Sikkim.", type: "sightseeing" },
          { _key: "sk7b", title: "Pemayangtse Monastery", description: "One of Sikkim's oldest and most important monasteries (founded ~1705).", location: { name: "Pemayangtse Monastery", lat: 27.2144, lng: 88.2436 }, type: "sightseeing" },
          { _key: "sk7c", title: "Rabdentse Ruins", description: "Ruins of the second capital of Sikkim, set in the forest above Pelling.", type: "sightseeing" },
          { _key: "sk7d", title: "Depart for Bagdogra/NJP", description: "~5 hr drive. Keep buffer time near Siliguri traffic. Evening flight or train onward.", location: { name: "Bagdogra Airport", lat: 26.6812, lng: 88.3286 }, type: "transport" },
        ],
      },
    ],
  },
  {
    _id: "trip-meghalaya-5-days",
    title: "5 Days in Meghalaya — Living Root Bridges, Dawki & Waterfalls",
    slug: "meghalaya-5-days",
    excerpt:
      "Shillong's misty hills, Cherrapunji's record-breaking waterfalls, the double-decker living root bridge trek to Nongriat, and a boat ride on the crystal-clear Umngot River at Dawki.",
    tags: ["Northeast", "Meghalaya", "Nature", "Trekking", "Waterfalls", "Adventure", "India"],
    country: "India",
    bestSuggestedMonth: "October – May",
    status: "published",
    viewCount: 521,
    totalBudget: 18000,
    currency: "INR",
    tripType: "Nature & Trekking",
    readingTime: 9,
    _createdAt: "2026-08-26T00:00:00Z",
    _updatedAt: "2026-08-26T00:00:00Z",
    coverImage: undefined,
    itinerary: [
      {
        _key: "mg-day1",
        dayNumber: 1,
        title: "Guwahati Arrival → Shillong",
        date: undefined,
        summary: "Transfer from Guwahati airport to the 'Scotland of the East', arriving in time for an evening walk through the vibrant Police Bazaar and a taste of Khasi cuisine.",
        activities: [
          { _key: "mg1a", title: "Land at Guwahati Airport", description: "Private cab to Shillong (~100 km, 3 hrs via NH-6). Lunch stop at Nongpoh en route.", location: { name: "Guwahati Airport (GAU)", lat: 26.1061, lng: 91.5859 }, type: "transport" },
          { _key: "mg1b", title: "Check-in Shillong hotel", description: "No special permit needed for Indian nationals. Foreign nationals arrange Protected Area Permit on arrival.", location: { name: "Shillong", lat: 25.5788, lng: 91.8933 }, type: "accommodation" },
          { _key: "mg1c", title: "Evening at Police Bazaar", description: "Shillong's bustling market hub — street food, local crafts, and Meghalaya vibes.", type: "activity" },
          { _key: "mg1d", title: "Dinner — Khasi cuisine", description: "Try Jadoh (rice and pork), Tungrymbai (fermented soybean), and Doh Khlieh.", type: "food" },
        ],
      },
      {
        _key: "mg-day2",
        dayNumber: 2,
        title: "Shillong Local Sightseeing",
        date: undefined,
        summary: "Umiam Lake boating, the tiered cascade of Elephant Falls, panoramic city views from Shillong Peak, and an evening at the neo-Gothic Cathedral of Mary Help of Christians.",
        activities: [
          { _key: "mg2a", title: "Umiam Lake", description: "Boating and photography on the large man-made reservoir above Shillong.", location: { name: "Umiam Lake", lat: 25.6667, lng: 91.8833 }, type: "activity" },
          { _key: "mg2b", title: "Elephant Falls", description: "Three-tier waterfall in a forested gorge near Shillong. Entry ₹20 pp.", location: { name: "Elephant Falls", lat: 25.5375, lng: 91.8256 }, type: "sightseeing" },
          { _key: "mg2c", title: "Shillong Peak viewpoint", description: "Highest point in Meghalaya with city panorama. Bring valid ID — Air Force restricted area.", type: "sightseeing" },
          { _key: "mg2d", title: "Ward's Lake & Lady Hydari Park", description: "Central Shillong's green lungs — boating and gardens.", type: "activity" },
          { _key: "mg2e", title: "Cathedral of Mary Help of Christians", description: "Beautiful Gothic church in central Shillong, lit up in the evening.", type: "sightseeing" },
        ],
      },
      {
        _key: "mg-day3",
        dayNumber: 3,
        title: "Shillong → Cherrapunji (Sohra)",
        date: undefined,
        summary: "Drive to one of the wettest places on Earth — Mawsmai limestone cave, Nohkalikai (India's tallest plunge waterfall), Seven Sisters Falls, and a homestay in Sohra.",
        activities: [
          { _key: "mg3a", title: "Drive to Cherrapunji", description: "~55 km, 1.5–2 hrs through scenic ghat roads.", type: "transport" },
          { _key: "mg3b", title: "Mawsmai Cave", description: "Narrow limestone cave with stalactites and stalagmites. Entry ₹30 pp. Not suitable for claustrophobic travelers.", location: { name: "Mawsmai Cave, Cherrapunji", lat: 25.2702, lng: 91.7323 }, type: "activity" },
          { _key: "mg3c", title: "Nohkalikai Falls", description: "India's tallest plunge waterfall (340 m). Most dramatic Sep–Oct just after monsoon.", location: { name: "Nohkalikai Falls", lat: 25.253, lng: 91.7161 }, type: "sightseeing" },
          { _key: "mg3d", title: "Seven Sisters Falls (Nohsngithiang)", description: "Seven parallel waterfalls cascading down the Meghalaya plateau.", type: "sightseeing" },
          { _key: "mg3e", title: "Eco Park / Thangkharang Park", description: "Viewpoint overlooking the Bangladesh plains below the Cherrapunji cliffs.", type: "sightseeing" },
          { _key: "mg3f", title: "Check-in Cherrapunji homestay", description: "Overnight in Sohra with views across the deep valley.", type: "accommodation" },
        ],
      },
      {
        _key: "mg-day4",
        dayNumber: 4,
        title: "Double Decker Root Bridge Trek & Dawki",
        date: undefined,
        summary: "The flagship Meghalaya experience — the gruelling 3,500-step descent and ascent to the double-decker living root bridge at Nongriat, then drive to the crystal-clear Umngot River at Dawki.",
        activities: [
          { _key: "mg4a", title: "Early breakfast, drive to Tyrna village", description: "Trek trailhead for the Nongriat Living Root Bridge. Leave by 6:30 AM.", type: "transport" },
          { _key: "mg4b", title: "Trek to Double Decker Living Root Bridge", description: "~3,500 steps down to Nongriat (~2.5–3 hrs one way). Wear grip shoes, carry water. Steep and demanding — not suitable for knee issues.", location: { name: "Double Decker Root Bridge, Nongriat", lat: 25.2496, lng: 91.7247 }, type: "activity" },
          { _key: "mg4c", title: "Rainbow Falls swim", description: "Natural pool at Rainbow Falls near Nongriat — turquoise water surrounded by jungle.", type: "activity" },
          { _key: "mg4d", title: "Trek back to Tyrna", description: "~2–2.5 hrs climbing back up 3,500 steps.", type: "activity" },
          { _key: "mg4e", title: "Drive to Dawki, sunset at Umngot River", description: "Check-in at Dawki homestay. Sunset at the crystal-clear Umngot River, one of Asia's clearest rivers.", location: { name: "Dawki, Umngot River", lat: 25.1892, lng: 92.0197 }, type: "accommodation" },
        ],
      },
      {
        _key: "mg-day5",
        dayNumber: 5,
        title: "Dawki River Boating & Departure",
        date: undefined,
        summary: "Morning boat ride on the transparent Umngot River — boats appear to float in mid-air — optional visit to Mawlynnong (cleanest village in Asia), then drive back to Guwahati.",
        activities: [
          { _key: "mg5a", title: "Boating on Umngot River", description: "Best in winter months when water is at its clearest. Shared boat ~₹500.", location: { name: "Umngot River, Dawki", lat: 25.1917, lng: 92.0181 }, type: "activity" },
          { _key: "mg5b", title: "Mawlynnong village (optional)", description: "Cleanest village in Asia — bamboo-lined paths, single-decker root bridge, tree-house viewpoint.", type: "sightseeing" },
          { _key: "mg5c", title: "Drive to Guwahati Airport", description: "~4 hrs. Keep buffer time for the long return drive.", location: { name: "Guwahati Airport", lat: 26.1061, lng: 91.5859 }, type: "transport" },
        ],
      },
    ],
  },
  {
    _id: "trip-kerala-7-days",
    title: "7 Days in Kerala — Fort Kochi, Munnar, Backwaters & Kovalam",
    slug: "kerala-7-days",
    excerpt:
      "Fort Kochi's Chinese fishing nets and Kathakali, Munnar's tea-carpeted hills and Nilgiri Tahr, Thekkady's spice plantation and Periyar tiger reserve, an overnight backwater houseboat on Vembanad Lake, and Kovalam's lighthouse beach.",
    tags: ["South India", "Kerala", "Coastal", "Mountains", "Culture", "Food", "Beach", "India"],
    country: "India",
    startDate: undefined,
    endDate: undefined,
    bestSuggestedMonth: "September – March",
    status: "published",
    viewCount: 874,
    totalBudget: 30000,
    currency: "INR",
    tripType: "Backwaters, Hills & Beach",
    readingTime: 13,
    _createdAt: "2026-08-26T00:00:00Z",
    _updatedAt: "2026-08-26T00:00:00Z",
    coverImage: undefined,
    itinerary: [
      {
        _key: "kl-day1",
        dayNumber: 1,
        title: "Kochi Arrival — Fort Kochi Exploration",
        date: undefined,
        summary: "Land at Kochi, settle into Fort Kochi's colonial streets, see the iconic Chinese fishing nets, St. Francis Church, Jew Town, and an evening Kathakali performance.",
        activities: [
          { _key: "kl1a", title: "Land at Kochi Airport, transfer to Fort Kochi", description: "~45 min drive. Kerala fish curry and appam for lunch.", location: { name: "Fort Kochi", lat: 9.9658, lng: 76.2422 }, type: "transport" },
          { _key: "kl1b", title: "Chinese Fishing Nets", description: "Iconic cantilevered fishing nets along the Fort Kochi waterfront — best at sunset.", type: "sightseeing" },
          { _key: "kl1c", title: "Santa Cruz Basilica & St. Francis Church", description: "St. Francis Church is where Vasco da Gama was originally buried — one of India's oldest European churches.", type: "sightseeing" },
          { _key: "kl1d", title: "Jew Town & Mattancherry Palace", description: "Browse the antique shops of Jew Town and visit the Dutch Palace with Kerala murals.", location: { name: "Mattancherry, Kochi", lat: 9.9557, lng: 76.2574 }, type: "sightseeing" },
          { _key: "kl1e", title: "Kathakali dance performance", description: "Book tickets in advance; arrive 30 min early for the make-up demonstration. ₹400 pp.", type: "activity" },
        ],
      },
      {
        _key: "kl-day2",
        dayNumber: 2,
        title: "Kochi → Munnar",
        date: undefined,
        summary: "Scenic 4-hour ghat road drive to the tea capital of South India, stopping at Cheeyappara and Valara waterfalls along the way.",
        activities: [
          { _key: "kl2a", title: "Drive Kochi → Munnar (~130 km, 4 hrs)", description: "Carry motion sickness tablets — roads have many hairpin bends. Temperature drops noticeably on ascent.", type: "transport" },
          { _key: "kl2b", title: "Cheeyappara & Valara Waterfalls", description: "Roadside waterfalls on the Kochi–Munnar ghat road — worth a quick stop.", type: "sightseeing" },
          { _key: "kl2c", title: "Arrive Munnar, check-in", description: "Visit a local spice/tea shop for a first taste of Munnar's aromatic produce.", location: { name: "Munnar", lat: 10.0889, lng: 77.0595 }, type: "accommodation" },
        ],
      },
      {
        _key: "kl-day3",
        dayNumber: 3,
        title: "Munnar Sightseeing",
        date: undefined,
        summary: "Sunrise at Top Station, Nilgiri Tahr spotting at Eravikulam National Park, Mattupetty Dam, boating on Kundala Lake, and the Tea Museum.",
        activities: [
          { _key: "kl3a", title: "Sunrise at Top Station viewpoint", description: "Highest point on the Munnar–Kodaikanal road with views into Tamil Nadu.", type: "sightseeing" },
          { _key: "kl3b", title: "Eravikulam National Park", description: "Nilgiri Tahr habitat — Munnar's rarest attraction. Park closes Feb–Mar some years for breeding. Entry + shuttle ₹150 pp.", location: { name: "Eravikulam National Park", lat: 10.1667, lng: 77.05 }, type: "activity" },
          { _key: "kl3c", title: "Mattupetty Dam & Echo Point", description: "Scenic dam with boat rides and an echo phenomenon nearby.", type: "sightseeing" },
          { _key: "kl3d", title: "Kundala Lake boating", description: "Pedal boats on a picturesque lake surrounded by tea gardens.", location: { name: "Kundala Lake, Munnar", lat: 10.1167, lng: 77.1167 }, type: "activity" },
          { _key: "kl3e", title: "Tea Museum", description: "History of Munnar's tea plantations from the British colonial era. ₹150 pp.", type: "sightseeing" },
        ],
      },
      {
        _key: "kl-day4",
        dayNumber: 4,
        title: "Munnar → Thekkady",
        date: undefined,
        summary: "Drive into the spice heartland — guided cardamom and pepper plantation tour, then a Periyar Lake boat safari with chances of spotting wild elephants and bison.",
        activities: [
          { _key: "kl4a", title: "Drive Munnar → Thekkady (~110 km, 3.5 hrs)", type: "transport" },
          { _key: "kl4b", title: "Guided spice plantation tour", description: "Walk among cardamom, pepper, cinnamon, and vanilla vines. ₹200 pp.", location: { name: "Thekkady/Periyar Tiger Reserve", lat: 9.5916, lng: 77.1611 }, type: "activity" },
          { _key: "kl4c", title: "Periyar Lake boat safari", description: "Book in advance — early morning slots have better wildlife sightings. Elephants, bison, and rare birds. ₹300 pp.", type: "activity" },
          { _key: "kl4d", title: "Kalaripayattu martial arts show (optional)", description: "Kerala's ancient martial art form — an evening cultural show. ₹350 pp.", type: "activity" },
        ],
      },
      {
        _key: "kl-day5",
        dayNumber: 5,
        title: "Thekkady → Alleppey — Houseboat Overnight",
        date: undefined,
        summary: "Drive to Alleppey and board a traditional Kettuvallam houseboat for an overnight cruise through Vembanad Lake, Kerala's backwater canals, and village waterways.",
        activities: [
          { _key: "kl5a", title: "Drive Thekkady → Alleppey (~140 km, 4 hrs)", type: "transport" },
          { _key: "kl5b", title: "Board houseboat — welcome lunch onboard", description: "Traditional Kettuvallam with AC bedroom. Confirm veg/non-veg meals with operator beforehand.", location: { name: "Alleppey Backwaters", lat: 9.4981, lng: 76.3388 }, type: "accommodation" },
          { _key: "kl5c", title: "Cruise through Vembanad Lake & narrow canals", description: "Sunset over the backwaters, evening snacks, and village life along the waterways.", type: "activity" },
          { _key: "kl5d", title: "Dinner onboard — overnight stay", description: "Fresh backwater fish and Kerala specialties cooked by the houseboat chef.", type: "food" },
        ],
      },
      {
        _key: "kl-day6",
        dayNumber: 6,
        title: "Alleppey → Kovalam Beach",
        date: undefined,
        summary: "Disembark the houseboat and drive south to Kerala's most famous beach resort, arriving in time for a relaxed afternoon at Lighthouse Beach and a seafood dinner.",
        activities: [
          { _key: "kl6a", title: "Disembark houseboat after breakfast", description: "Check-out around 9 AM.", type: "transport" },
          { _key: "kl6b", title: "Drive Alleppey → Kovalam (~160 km, 4 hrs)", type: "transport" },
          { _key: "kl6c", title: "Lighthouse Beach, Kovalam", description: "Relax on the crescent beach. Swim only in flagged zones. Lighthouse climb for panoramic views (small fee).", location: { name: "Kovalam", lat: 8.3988, lng: 76.9781 }, type: "activity" },
          { _key: "kl6d", title: "Sunset at Kovalam Lighthouse", description: "The lighthouse offers a 360° view of Kerala's southern coastline at golden hour.", type: "sightseeing" },
          { _key: "kl6e", title: "Seafood dinner by the beach", description: "Fresh catch — Karimeen (pearl spot fish), prawns, or lobster at the beach shacks.", type: "food" },
        ],
      },
      {
        _key: "kl-day7",
        dayNumber: 7,
        title: "Kovalam Leisure — Departure from Trivandrum",
        date: undefined,
        summary: "Optional Ayurvedic massage, a final beach walk, then transfer to Trivandrum Airport for the return flight.",
        activities: [
          { _key: "kl7a", title: "Ayurvedic massage session (optional)", description: "Book with Kerala Tourism-approved centers only. ₹1,200 pp.", type: "activity" },
          { _key: "kl7b", title: "Beach leisure & souvenir shopping", description: "Last chance for Kerala spices, coconut products, and handicrafts.", type: "activity" },
          { _key: "kl7c", title: "Depart for Trivandrum Airport", description: "~20 km / 40 min. Allow buffer time — Trivandrum city traffic can be unpredictable.", location: { name: "Trivandrum Airport (TRV)", lat: 8.4821, lng: 76.92 }, type: "transport" },
        ],
      },
    ],
  },
  {
    _id: "trip-munsiyari-6-days",
    title: "Munsiyari Trip from Haridwar — 6 Days in Kumaon",
    slug: "munsiyari-6-days",
    excerpt:
      "Road trip through the Kumaon Himalayas from Haridwar to Munsiyari — the 'Little Kashmir' of Uttarakhand — stopping at Kausani's Himalayan panorama, trekking to Khaliya Top for Panchachuli views, and ending with Ganga Aarti at Haridwar.",
    tags: ["Himalayas", "Uttarakhand", "Road Trip", "Mountains", "Adventure", "Trekking", "India", "High Altitude"],
    country: "India",
    bestSuggestedMonth: "April – June & September – November",
    status: "published",
    viewCount: 389,
    totalBudget: 17000,
    currency: "INR",
    tripType: "Road Trip",
    readingTime: 10,
    _createdAt: "2026-08-26T00:00:00Z",
    _updatedAt: "2026-08-26T00:00:00Z",
    coverImage: undefined,
    itinerary: [
      {
        _key: "mu-day1",
        dayNumber: 1,
        title: "Haridwar → Kausani",
        date: undefined,
        summary: "Begin the Kumaon road trip from Haridwar, climbing through Kathgodam and Almora to Kausani — Switzerland of India — arriving in time for a Trishul and Nanda Devi sunset.",
        activities: [
          { _key: "mu1a", title: "Depart Haridwar (~250 km, 8–9 hrs)", description: "Start early to avoid driving winding Kumaon roads after dark.", location: { name: "Haridwar", lat: 29.9457, lng: 78.1642 }, type: "transport" },
          { _key: "mu1b", title: "Breakfast stop at Kathgodam", description: "Gateway to Kumaon — last major plains town before the hills.", type: "food" },
          { _key: "mu1c", title: "Lunch & brief stop at Almora", description: "Almora market and Bright Corner viewpoint — the cultural capital of Kumaon.", location: { name: "Almora", lat: 29.5971, lng: 79.6586 }, type: "activity" },
          { _key: "mu1d", title: "Arrive Kausani, sunset views", description: "Check-in with Trishul (7,120 m) and Nanda Devi (7,816 m) visible at sunset. Called the 'Switzerland of India'.", location: { name: "Kausani", lat: 29.8422, lng: 79.6062 }, type: "accommodation" },
        ],
      },
      {
        _key: "mu-day2",
        dayNumber: 2,
        title: "Kausani → Munsiyari",
        date: undefined,
        summary: "Sunrise at Anasakti Ashram viewpoint then the long Kumaon drive to Munsiyari — stopping at the ancient Baijnath Temple and the roadside Birthi Falls waterfall.",
        activities: [
          { _key: "mu2a", title: "Sunrise at Kausani — Anasakti Ashram viewpoint", description: "Gandhi meditated here in 1929 — now a tranquil sunrise spot with wide Himalayan views.", type: "sightseeing" },
          { _key: "mu2b", title: "Drive to Munsiyari via Bageshwar (~230 km, 7–8 hrs)", description: "Fuel up in Bageshwar — limited petrol pumps beyond this point.", type: "transport" },
          { _key: "mu2c", title: "Baijnath Temple", description: "Ancient Katyuri-era Shiva temple (~11th century) with fine stone carvings.", location: { name: "Baijnath Temple, Bageshwar", lat: 29.8289, lng: 79.6208 }, type: "sightseeing" },
          { _key: "mu2d", title: "Birthi Falls", description: "Beautiful roadside waterfall cascading through pine forest — roads narrow considerably after this point.", location: { name: "Birthi Falls", lat: 29.9833, lng: 80.1167 }, type: "sightseeing" },
          { _key: "mu2e", title: "Arrive Munsiyari, check-in", description: "The 'Little Kashmir' — panoramic views of the Panchachuli five-peak range.", location: { name: "Munsiyari", lat: 30.0668, lng: 80.2377 }, type: "accommodation" },
        ],
      },
      {
        _key: "mu-day3",
        dayNumber: 3,
        title: "Munsiyari — Khaliya Top Trek",
        date: undefined,
        summary: "Trek to Khaliya Top alpine meadow at 3,500 m for close-up Panchachuli five-peak views, then the Tribal Heritage Museum and sunset at Munsiyari viewpoint.",
        activities: [
          { _key: "mu3a", title: "Trek to Khaliya Top", description: "~5 km, 3–4 hrs round trip. Alpine meadow at ~3,500 m. Hire a local guide (~₹800/day). Carry trekking shoes and walking stick.", location: { name: "Khaliya Top", lat: 30.0833, lng: 80.2333 }, type: "activity" },
          { _key: "mu3b", title: "Summit views of Panchachuli peaks", description: "Five-peak massif dominating the eastern Kumaon skyline — one of Uttarakhand's most dramatic panoramas.", type: "sightseeing" },
          { _key: "mu3c", title: "Tribal Heritage Museum", description: "Small museum documenting the Bhotiya people — traditional clothes, tools, and culture. ₹30 pp.", type: "activity" },
          { _key: "mu3d", title: "Nanda Devi Temple & sunset viewpoint", description: "Temple dedicated to the goddess Nanda Devi, with Munsiyari's best sunset vantage.", type: "sightseeing" },
        ],
      },
      {
        _key: "mu-day4",
        dayNumber: 4,
        title: "Munsiyari — Balati Village & Gori Ganga Valley",
        date: undefined,
        summary: "A cultural immersion day with the Bhotiya weaving community in Balati village, a walk along the Gori Ganga river, and an optional bonfire evening.",
        activities: [
          { _key: "mu4a", title: "Drive to Balati Village", description: "Traditional Bhotiya weaving community. Observe and buy wool shawls and carpets directly from artisans.", location: { name: "Balati Village, Gori Ganga Valley", lat: 30.05, lng: 80.23 }, type: "activity" },
          { _key: "mu4b", title: "Walk along Gori Ganga riverbank", description: "Short walk along the glacier-fed Gori Ganga river through the valley.", type: "activity" },
          { _key: "mu4c", title: "Visit Darkot village or relax at hotel", description: "Flexible buffer day — also useful as an acclimatization/rest day after the Khaliya Top trek.", type: "activity" },
          { _key: "mu4d", title: "Bonfire evening (seasonal)", description: "Weather permitting — a cozy end to the day in the mountains.", type: "activity" },
        ],
      },
      {
        _key: "mu-day5",
        dayNumber: 5,
        title: "Munsiyari → Kausani (Return)",
        date: undefined,
        summary: "Begin the return drive through Bageshwar, with an optional stop at Chitai Golu Devta Temple — famous for thousands of bells — before arriving back at Kausani.",
        activities: [
          { _key: "mu5a", title: "Drive Munsiyari → Kausani via Bageshwar (~230 km, 7–8 hrs)", type: "transport" },
          { _key: "mu5b", title: "Lunch at Bageshwar", type: "food" },
          { _key: "mu5c", title: "Chitai Golu Devta Temple (optional)", description: "Famous for thousands of bells left by devotees as offerings — worth a 20-min stop.", location: { name: "Chitai Golu Devta Temple", lat: 29.6486, lng: 79.6642 }, type: "sightseeing" },
          { _key: "mu5d", title: "Arrive Kausani, overnight rest", location: { name: "Kausani", lat: 29.8422, lng: 79.6062 }, type: "accommodation" },
        ],
      },
      {
        _key: "mu-day6",
        dayNumber: 6,
        title: "Kausani → Haridwar — Departure",
        date: undefined,
        summary: "The final drive back from the hills to Haridwar, timed to arrive for the evening Ganga Aarti — one of India's most moving spiritual ceremonies.",
        activities: [
          { _key: "mu6a", title: "Drive Kausani → Haridwar (~250 km, 8–9 hrs)", description: "Start early to reach Haridwar before the 6:30–7:00 PM aarti.", type: "transport" },
          { _key: "mu6b", title: "Lunch stop at Kathgodam", type: "food" },
          { _key: "mu6c", title: "Evening Ganga Aarti at Har Ki Pauri", description: "A fitting end to the Kumaon trip — priests chant, bells ring, and oil lamp floats lit on the Ganga.", location: { name: "Har Ki Pauri, Haridwar", lat: 29.9457, lng: 78.1642 }, type: "activity" },
        ],
      },
    ],
  },
  {
    _id: "trip-char-dham-yatra",
    title: "Char Dham Yatra Uttarakhand — 10 Days",
    slug: "char-dham-yatra-uttarakhand",
    excerpt:
      "The complete Char Dham circuit: Yamunotri, Gangotri, Kedarnath, and Badrinath — four sacred shrines in the Garhwal Himalayas. Includes the 16 km Kedarnath trek, the Gangotri glacier source of the Ganga, and the last village of India at Mana.",
    tags: ["Himalayas", "Uttarakhand", "Trekking", "Heritage", "Culture", "India", "Pilgrimage", "Adventure"],
    country: "India",
    bestSuggestedMonth: "May – June & September – October",
    status: "published",
    viewCount: 712,
    totalBudget: 38000,
    currency: "INR",
    tripType: "Pilgrimage Trek",
    readingTime: 16,
    _createdAt: "2026-08-26T00:00:00Z",
    _updatedAt: "2026-08-26T00:00:00Z",
    coverImage: undefined,
    itinerary: [
      {
        _key: "cd-day1",
        dayNumber: 1,
        title: "Arrival at Haridwar",
        date: undefined,
        summary: "Arrive in Haridwar, collect Char Dham biometric registration e-pass, and attend the iconic Ganga Aarti at Har Ki Pauri — the spiritual gateway to the yatra.",
        activities: [
          { _key: "cd1a", title: "Arrive Haridwar", description: "By train or via Dehradun airport. Get medical fitness check if you have heart/BP conditions.", location: { name: "Haridwar", lat: 29.9457, lng: 78.1642 }, type: "transport" },
          { _key: "cd1b", title: "Collect Char Dham e-pass", description: "Mandatory biometric registration via Uttarakhand Tourism portal — checked at all dham checkpoints.", type: "activity" },
          { _key: "cd1c", title: "Evening Ganga Aarti at Har Ki Pauri", description: "Priests chant, conch shells sound, and oil lamps float on the sacred Ganga.", type: "sightseeing" },
        ],
      },
      {
        _key: "cd-day2",
        dayNumber: 2,
        title: "Haridwar → Barkot (Yamunotri Base)",
        date: undefined,
        summary: "Long drive through Mussoorie hills to Barkot — the base camp for the Yamunotri trek. Last major ATM and fuel stop before the trek.",
        activities: [
          { _key: "cd2a", title: "Drive Haridwar → Barkot (~170 km, 6–7 hrs)", description: "Breakfast stop near Mussoorie/Kempty area.", type: "transport" },
          { _key: "cd2b", title: "Arrive Barkot, rest and prepare", description: "Barkot has the last major ATM and fuel before Janki Chatti. Early rest for the Yamunotri trek.", location: { name: "Barkot", lat: 30.8167, lng: 78.2167 }, type: "accommodation" },
        ],
      },
      {
        _key: "cd-day3",
        dayNumber: 3,
        title: "Yamunotri Darshan",
        date: undefined,
        summary: "Trek 6 km from Janki Chatti to Yamunotri Temple (3,293 m) — the source of river Yamuna — for a holy dip at the Surya Kund hot spring. Cook rice in the hot spring as tradition demands.",
        activities: [
          { _key: "cd3a", title: "Drive to Janki Chatti, begin Yamunotri trek", description: "~6 km trek (4–5 hrs). Pony ~₹1,300 pp or palki (stretcher) available for those unable to walk.", type: "activity" },
          { _key: "cd3b", title: "Darshan at Yamunotri Temple & Surya Kund", description: "Surya Kund hot spring reaches ~94°C — pilgrims cook rice wrapped in cloth as a prasad offering.", location: { name: "Yamunotri Temple", lat: 31.01, lng: 78.45 }, type: "sightseeing" },
          { _key: "cd3c", title: "Descend to Janki Chatti, drive to Barkot/Uttarkashi", description: "Overnight in Barkot or Uttarkashi.", type: "accommodation" },
        ],
      },
      {
        _key: "cd-day4",
        dayNumber: 4,
        title: "Gangotri Darshan",
        date: undefined,
        summary: "Drive to Gangotri Temple (3,100 m) on the banks of the Bhagirathi — the origin of the sacred Ganga — the easiest of the four dhams (no major trek required).",
        activities: [
          { _key: "cd4a", title: "Drive Uttarkashi → Gangotri (~100 km, 4 hrs)", type: "transport" },
          { _key: "cd4b", title: "Darshan at Gangotri Temple", description: "Sacred temple on the banks of the Bhagirathi river, surrounded by snow peaks.", location: { name: "Gangotri Temple", lat: 30.9946, lng: 78.9398 }, type: "sightseeing" },
          { _key: "cd4c", title: "Bhagirath Shila & riverside ghats", description: "Rock where King Bhagirath meditated to bring the Ganga to earth — a key pilgrimage spot.", type: "sightseeing" },
          { _key: "cd4d", title: "Return drive to Uttarkashi", description: "Overnight in Uttarkashi.", type: "accommodation" },
        ],
      },
      {
        _key: "cd-day5",
        dayNumber: 5,
        title: "Uttarkashi → Guptkashi (via Rudraprayag)",
        date: undefined,
        summary: "Long transit day connecting the Yamunotri/Gangotri circuit to the Kedarnath/Badrinath circuit — stop at the Alaknanda-Mandakini river confluence at Rudraprayag.",
        activities: [
          { _key: "cd5a", title: "Drive Uttarkashi → Guptkashi (~220 km, 7–8 hrs)", description: "Long transit day — start early.", type: "transport" },
          { _key: "cd5b", title: "Lunch at Srinagar (Uttarakhand)", type: "food" },
          { _key: "cd5c", title: "Brief stop at Rudraprayag", description: "Confluence of the Alaknanda and Mandakini rivers — one of Garhwal's sacred prayags.", location: { name: "Rudraprayag", lat: 30.2858, lng: 78.9814 }, type: "sightseeing" },
          { _key: "cd5d", title: "Arrive Guptkashi, pack light bags for Kedarnath", description: "Leave heavy luggage at hotel. Take only essentials for the Kedarnath trek.", location: { name: "Guptkashi", lat: 30.5333, lng: 79.0667 }, type: "accommodation" },
        ],
      },
      {
        _key: "cd-day6",
        dayNumber: 6,
        title: "Kedarnath Trek & Arrival",
        date: undefined,
        summary: "The longest and most challenging leg — 16–18 km trek from Gaurikund to Kedarnath temple (3,583 m). Helicopter option available for those skipping the trek.",
        activities: [
          { _key: "cd6a", title: "Drive to Gaurikund, begin Kedarnath trek", description: "~16–18 km, 6–8 hrs. Pony ₹3,500–4,000. Helicopter (Phata/Guptkashi) ₹7,500–9,000 one-way — book weeks ahead.", type: "activity" },
          { _key: "cd6b", title: "Arrive Kedarnath, evening aarti", description: "Check-in at guesthouse or dharamshala at 3,583 m. Evening aarti at the ancient temple.", location: { name: "Kedarnath", lat: 30.7346, lng: 79.0669 }, type: "accommodation" },
        ],
      },
      {
        _key: "cd-day7",
        dayNumber: 7,
        title: "Kedarnath Darshan — Descend to Guptkashi",
        date: undefined,
        summary: "Sunrise darshan at Kedarnath temple, visit Bhairav Temple and Adi Shankaracharya Samadhi, then begin the descent back to Gaurikund.",
        activities: [
          { _key: "cd7a", title: "Early morning darshan at Kedarnath Temple", description: "5 AM queue for morning puja — one of the twelve Jyotirlingas of Shiva.", location: { name: "Kedarnath Temple", lat: 30.7346, lng: 79.0669 }, type: "sightseeing" },
          { _key: "cd7b", title: "Bhairav Temple & Adi Shankaracharya Samadhi", description: "Shankaracharya is said to have attained mahasamadhi here in the 8th century.", type: "sightseeing" },
          { _key: "cd7c", title: "Descend to Gaurikund, drive to Guptkashi", description: "5–6 hrs descent on foot. Start early to avoid trekking after dark.", type: "transport" },
        ],
      },
      {
        _key: "cd-day8",
        dayNumber: 8,
        title: "Guptkashi → Badrinath (via Joshimath)",
        date: undefined,
        summary: "Drive north through Joshimath and past Vishnuprayag to reach Badrinath — the abode of Lord Vishnu at 3,133 m — for the evening aarti.",
        activities: [
          { _key: "cd8a", title: "Drive Guptkashi → Badrinath (~200 km, 7–8 hrs)", description: "Check road status near Joshimath — landslide-prone stretch.", type: "transport" },
          { _key: "cd8b", title: "Lunch at Joshimath", description: "Gateway to Badrinath — also base for Auli ski resort and Valley of Flowers.", location: { name: "Joshimath", lat: 30.5546, lng: 79.5658 }, type: "food" },
          { _key: "cd8c", title: "Evening darshan at Badrinath Temple", description: "Colourful facade of the temple lit up at dusk — one of the most iconic images of the Char Dham.", location: { name: "Badrinath", lat: 30.7433, lng: 79.4938 }, type: "sightseeing" },
        ],
      },
      {
        _key: "cd-day9",
        dayNumber: 9,
        title: "Badrinath Darshan — Drive to Rudraprayag/Srinagar",
        date: undefined,
        summary: "Early Badrinath darshan, then Mana Village — the last village before the Tibetan border — Vyas Gufa, Bhim Pul, and a dip in the Tapt Kund hot spring.",
        activities: [
          { _key: "cd9a", title: "Early darshan at Badrinath Temple", description: "5 AM puja to avoid the day's crowds.", location: { name: "Badrinath Temple", lat: 30.7433, lng: 79.4938 }, type: "sightseeing" },
          { _key: "cd9b", title: "Mana Village — last Indian village", description: "Bring ID — border proximity. Vyas Gufa (cave where the Mahabharata was dictated), Bhim Pul (natural rock bridge).", location: { name: "Mana Village", lat: 30.7681, lng: 79.4909 }, type: "sightseeing" },
          { _key: "cd9c", title: "Tapt Kund hot spring dip", description: "Sulfuric hot spring near the Badrinath temple complex — sacred ritual bath.", type: "activity" },
          { _key: "cd9d", title: "Drive to Rudraprayag/Srinagar", description: "Char Dham circuit complete. Overnight before the final return leg.", type: "accommodation" },
        ],
      },
      {
        _key: "cd-day10",
        dayNumber: 10,
        title: "Return to Haridwar — Departure",
        date: undefined,
        summary: "Final drive back to Haridwar, stopping at Devprayag — where the Bhagirathi and Alaknanda merge to officially form the Ganga — a meaningful final moment.",
        activities: [
          { _key: "cd10a", title: "Drive toward Haridwar (~160 km, 5–6 hrs)", type: "transport" },
          { _key: "cd10b", title: "Breakfast stop at Devprayag", description: "Where Bhagirathi + Alaknanda merge to form the Ganga — a sacred and scenic confluence.", location: { name: "Devprayag", lat: 30.1462, lng: 78.5983 }, type: "sightseeing" },
          { _key: "cd10c", title: "Arrive Haridwar, departure", description: "Char Dham Yatra complete — four sacred dhams in the Garhwal Himalayas.", location: { name: "Haridwar", lat: 29.9457, lng: 78.1642 }, type: "activity" },
        ],
      },
    ],
  },
  {
    _id: "trip-panch-kedar-trek",
    title: "Panch Kedar Trek — All 5 Sacred Shiva Shrines in 10 Days",
    slug: "panch-kedar-trek-10-days",
    excerpt:
      "The ultimate Garhwal Himalayan pilgrimage circuit — trekking all five Kedar shrines: Kedarnath, Tungnath (world's highest Shiva temple), Madhyamaheshwar, Rudranath (most remote), and Kalpeshwar. A 10-day fast-paced adventure requiring strong fitness.",
    tags: ["Himalayas", "Uttarakhand", "Trekking", "Adventure", "Heritage", "Culture", "India", "High Altitude", "Pilgrimage"],
    country: "India",
    bestSuggestedMonth: "May – June & September – October",
    status: "published",
    viewCount: 298,
    totalBudget: 26000,
    currency: "INR",
    tripType: "Multi-site Pilgrimage Trek",
    readingTime: 17,
    _createdAt: "2026-08-26T00:00:00Z",
    _updatedAt: "2026-08-26T00:00:00Z",
    coverImage: undefined,
    itinerary: [
      {
        _key: "pk-day1",
        dayNumber: 1,
        title: "Haridwar → Sonprayag/Guptkashi",
        date: undefined,
        summary: "Drive from Haridwar into the Garhwal hills, arriving at Sonprayag to begin the Panch Kedar circuit. Kedarnath e-pass registration required in advance.",
        activities: [
          { _key: "pk1a", title: "Drive Haridwar → Sonprayag (~220 km, 8 hrs)", description: "Lunch at Rudraprayag (Alaknanda-Mandakini confluence).", location: { name: "Sonprayag", lat: 30.6167, lng: 78.95 }, type: "transport" },
          { _key: "pk1b", title: "Rest, prepare trek gear", description: "Register for Kedarnath e-pass online in advance — checked at Sonprayag checkpoint. Carry trekking poles and layered clothing.", type: "activity" },
        ],
      },
      {
        _key: "pk-day2",
        dayNumber: 2,
        title: "Sonprayag → Gaurikund → Kedarnath Trek (Kedar 1/5)",
        date: undefined,
        summary: "Cab to Gaurikund, then the 16–18 km trek to Kedarnath (3,583 m) — the first and most famous of the five Kedar shrines — arriving in time for evening aarti.",
        activities: [
          { _key: "pk2a", title: "Cab to Gaurikund, begin trek", description: "16–18 km, 6–8 hrs. Pony available ~₹3,500–4,000 for those conserving energy for the days ahead.", type: "activity" },
          { _key: "pk2b", title: "Kedarnath Temple — evening aarti", description: "**Kedar 1 of 5** — the most famous Jyotirlinga, set against the Kedar Dome peak at 3,583 m.", location: { name: "Kedarnath", lat: 30.7346, lng: 79.0669 }, type: "sightseeing" },
          { _key: "pk2c", title: "Overnight at guesthouse/dharamshala", description: "Basic facilities — carry sleeping bag liner.", type: "accommodation" },
        ],
      },
      {
        _key: "pk-day3",
        dayNumber: 3,
        title: "Kedarnath Sunrise Darshan — Descend to Ukhimath",
        date: undefined,
        summary: "Sunrise puja at Kedarnath, descend to Gaurikund, then drive to Ukhimath — the winter seat of the Kedarnath deity — for a quick visit to Omkareshwar Temple.",
        activities: [
          { _key: "pk3a", title: "Sunrise darshan at Kedarnath Temple", description: "5 AM morning puja — the most auspicious time. Kedar 1 complete.", location: { name: "Kedarnath Temple", lat: 30.7346, lng: 79.0669 }, type: "sightseeing" },
          { _key: "pk3b", title: "Descent to Gaurikund (~6–7 hrs)", description: "Start early to avoid trekking after dark.", type: "activity" },
          { _key: "pk3c", title: "Drive to Ukhimath, Omkareshwar Temple", description: "Kedarnath deity resides here in winter. An atmospheric stop on the return.", location: { name: "Ukhimath", lat: 30.5333, lng: 79.1167 }, type: "sightseeing" },
        ],
      },
      {
        _key: "pk-day4",
        dayNumber: 4,
        title: "Ukhimath → Chopta — Tungnath Trek (Kedar 2/5)",
        date: undefined,
        summary: "The shortest and most accessible Kedar trek — 3.5 km to Tungnath, the world's highest Shiva temple at 3,680 m, with an optional extension to Chandrashila summit for 360° Himalayan views.",
        activities: [
          { _key: "pk4a", title: "Drive to Chopta (~40 km, 1.5 hrs)", description: "The 'Mini Switzerland of Uttarakhand' — stunning oak and rhododendron forests.", type: "transport" },
          { _key: "pk4b", title: "Trek to Tungnath Temple", description: "~3.5 km, 2.5–3 hrs. **Kedar 2 of 5** — world's highest Shiva temple at 3,680 m. Stone architecture dating back 1,000 years.", location: { name: "Tungnath", lat: 30.4897, lng: 79.2189 }, type: "activity" },
          { _key: "pk4c", title: "Chandrashila Summit (optional)", description: "~1.5 km further from Tungnath. 360° views of Nanda Devi, Trishul, Chaukhamba — highly recommended.", type: "sightseeing" },
          { _key: "pk4d", title: "Descend to Chopta, check-in", description: "Overnight in Chopta tents or guesthouses.", type: "accommodation" },
        ],
      },
      {
        _key: "pk-day5",
        dayNumber: 5,
        title: "Chopta → Ransi — Trek to Gaundar (Madhyamaheshwar Base)",
        date: undefined,
        summary: "Drive to Ransi village and begin trekking toward Madhyamaheshwar base camp at Gaundar — a quiet, less-commercialized route through terraced Garhwal villages.",
        activities: [
          { _key: "pk5a", title: "Drive Chopta → Ransi village (~35 km, 2 hrs)", type: "transport" },
          { _key: "pk5b", title: "Trek Ransi → Gaundar village (~9 km, 4–5 hrs)", description: "Base camp for Madhyamaheshwar. Carry cash — no ATMs beyond Ukhimath. Local guide recommended.", location: { name: "Gaundar Village", lat: 30.6167, lng: 79.2333 }, type: "activity" },
          { _key: "pk5c", title: "Rest and village exploration at Gaundar", description: "Peaceful terraced farmland village with Garhwali hospitality.", type: "accommodation" },
        ],
      },
      {
        _key: "pk-day6",
        dayNumber: 6,
        title: "Gaundar → Madhyamaheshwar Trek (Kedar 3/5)",
        date: undefined,
        summary: "The 9 km steady climb to Madhyamaheshwar (3,497 m) — third of the five Kedar shrines — with sweeping Chaukhamba peak views from the temple.",
        activities: [
          { _key: "pk6a", title: "Trek Gaundar → Madhyamaheshwar (~9 km, 5–6 hrs)", description: "Steady climb through bugyal meadows. Mules can carry heavier luggage for a fee.", type: "activity" },
          { _key: "pk6b", title: "Darshan at Madhyamaheshwar Temple", description: "**Kedar 3 of 5** — navel (nabhi) of Shiva according to Puranas, at 3,497 m. Chaukhamba (7,138 m) looms directly behind.", location: { name: "Madhyamaheshwar", lat: 30.6667, lng: 79.2167 }, type: "sightseeing" },
          { _key: "pk6c", title: "Overnight at temple guesthouse", description: "Very basic facilities — carry sleeping bag liner and personal medication.", type: "accommodation" },
        ],
      },
      {
        _key: "pk-day7",
        dayNumber: 7,
        title: "Descend Madhyamaheshwar → Drive to Gopeshwar",
        date: undefined,
        summary: "Descend from Madhyamaheshwar back to Gaundar then drive the long road to Gopeshwar — the gateway for the demanding Rudranath trek.",
        activities: [
          { _key: "pk7a", title: "Descend Madhyamaheshwar → Gaundar (~9 km, 4–5 hrs)", type: "activity" },
          { _key: "pk7b", title: "Drive Gaundar → Gopeshwar via Ransi (~70 km, 3 hrs)", description: "Long tiring transit day — pace yourself and hydrate.", type: "transport" },
          { _key: "pk7c", title: "Arrive Gopeshwar, rest for Rudranath", description: "Prepare for the toughest leg. Check gear and food supplies.", location: { name: "Gopeshwar", lat: 30.3833, lng: 79.3333 }, type: "accommodation" },
        ],
      },
      {
        _key: "pk-day8",
        dayNumber: 8,
        title: "Gopeshwar → Rudranath Trek (Kedar 4/5)",
        date: undefined,
        summary: "The hardest day of the entire circuit — 20 km through Panar Bugyal alpine meadows and dense forest to reach the most remote of the five shrines: Rudranath at 3,600 m. A mandatory local guide is not optional.",
        activities: [
          { _key: "pk8a", title: "Drive to Sagar village, begin Rudranath trek", description: "20 km one-way, 8–10 hrs through Panar Bugyal meadows. The toughest and most remote trek of the circuit.", type: "transport" },
          { _key: "pk8b", title: "Trek through Panar Bugyal to Rudranath", description: "Dense forest and alpine meadow crossing. Carry enough food and water — facilities minimal en route. Local guide mandatory.", location: { name: "Rudranath", lat: 30.4667, lng: 79.3333 }, type: "activity" },
          { _key: "pk8c", title: "Evening darshan at Rudranath Temple", description: "**Kedar 4 of 5** — the face (mukh) of Shiva. Temple carved into a natural rock face at 3,600 m.", type: "sightseeing" },
          { _key: "pk8d", title: "Overnight at basic guesthouse", type: "accommodation" },
        ],
      },
      {
        _key: "pk-day9",
        dayNumber: 9,
        title: "Rudranath Descent — Drive to Joshimath",
        date: undefined,
        summary: "Descend via the alternate Helang route (14 km) to reach the road head, then drive to Joshimath to prepare for the fifth and final Kedar.",
        activities: [
          { _key: "pk9a", title: "Alternate descent via Helang (~14 km, 6–7 hrs)", description: "Different trail from the ascent — confirm with guide which trailhead connects to Helang.", type: "activity" },
          { _key: "pk9b", title: "Drive Helang → Joshimath (~15 km, 30 min)", description: "Gateway to Badrinath and the Valley of Flowers.", location: { name: "Joshimath", lat: 30.5546, lng: 79.5658 }, type: "transport" },
          { _key: "pk9c", title: "Optional: Narsingh Temple, Joshimath", description: "Short evening walk to the historic Narsingh Temple in Joshimath town.", type: "activity" },
        ],
      },
      {
        _key: "pk-day10",
        dayNumber: 10,
        title: "Kalpeshwar Darshan (Kedar 5/5) — Return to Haridwar",
        date: undefined,
        summary: "The serene finale — a short 2 km walk to Kalpeshwar cave temple, the only Panch Kedar accessible without a major trek. Completing all five Kedars is considered highly auspicious. Then the long drive back to Haridwar.",
        activities: [
          { _key: "pk10a", title: "Drive to Urgam village, walk to Kalpeshwar", description: "~2 km easy walk from Urgam village to the cave temple.", type: "transport" },
          { _key: "pk10b", title: "Kalpeshwar Cave Temple — Panch Kedar circuit complete", description: "**Kedar 5 of 5** — the hair (jata) of Shiva. A serene cave temple, the most accessible of the five shrines. Circuit complete!", location: { name: "Kalpeshwar", lat: 30.5, lng: 79.4667 }, type: "sightseeing" },
          { _key: "pk10c", title: "Long drive Kalpeshwar → Haridwar (~230 km, 8 hrs)", description: "Arrive Haridwar/Rishikesh by evening. Panch Kedar complete.", location: { name: "Haridwar", lat: 29.9457, lng: 78.1642 }, type: "transport" },
        ],
      },
    ],
  },
  {
    _id: "trip-pune-konkan-raigad",
    title: "Pune – Konkan Coast – Raigad",
    slug: "pune-konkan-coast-raigad",
    excerpt:
      "A 4-Day / 5-Stop Coastal Loop — ~550–600 km from Pune down the Konkan coast and back via Raigad Fort.",
    tags: ["Road Trip", "Coastal", "Konkan", "Maharashtra", "India"],
    country: "India",
    bestSuggestedMonth: "October – February",
    status: "published",
    viewCount: 0,
    currency: "INR",
    tripType: "Road Trip",
    readingTime: 6,
    _createdAt: "2026-08-27T00:00:00Z",
    _updatedAt: "2026-08-27T00:00:00Z",
    coverImage: undefined,
    itinerary: [
      {
        _key: "pkr-day1",
        dayNumber: 1,
        title: "Pune to Anjarle",
        date: undefined,
        summary: "~180 km loop starting with misty ghats and ending at the cliffside temple of Anjarle.",
        activities: [
          { _key: "pkr1a", title: "Tamhini Ghat", description: "Waterfalls, misty ghats, and a great early-morning ride. Start here before the day heats up.", location: { name: "Tamhini Ghat", lat: 18.45, lng: 73.4167 }, type: "transport" },
          { _key: "pkr1b", title: "Mangaon → Ambet → Mandangad", description: "Winding ghat roads with small-town stops for chai and breakfast along the way.", location: { name: "Mandangad", lat: 17.9868, lng: 73.0487 }, type: "transport" },
          { _key: "pkr1c", title: "Anjarle & Kadyavarcha Ganpati", description: "Kadyavarcha Ganpati temple perched on a cliff, plus Anjarle beach.", location: { name: "Anjarle", lat: 17.85, lng: 73.0833 }, type: "sightseeing" },
          { _key: "pkr1d", title: "Overnight at Anjarle", description: "Rest after the ride.", type: "accommodation" },
        ],
      },
      {
        _key: "pkr-day2",
        dayNumber: 2,
        title: "Anjarle to Ganpatipule",
        date: undefined,
        summary: "~90 km coastal cruise past black-sand beaches and historic temples.",
        activities: [
          { _key: "pkr2a", title: "Murud (Kokan) & Ladghar", description: "Quiet black-sand beach at Murud, and clean, less-crowded Ladghar beach for a swim break.", location: { name: "Ladghar", lat: 17.6534, lng: 73.1365 }, type: "sightseeing" },
          { _key: "pkr2b", title: "Guhagar → Hedavi", description: "Hedavi's Ganpati temple and the Dashabhuja Ganesh idol.", location: { name: "Guhagar", lat: 17.4721, lng: 73.1977 }, type: "sightseeing" },
          { _key: "pkr2c", title: "Ganpatipule", description: "The famous Swayambhu Ganpati temple right on the beach.", location: { name: "Ganpatipule", lat: 17.1438, lng: 73.2687 }, type: "sightseeing" },
          { _key: "pkr2d", title: "Overnight at Ganpatipule", description: "Stay near the famous beachside temple.", type: "accommodation" },
        ],
      },
      {
        _key: "pkr-day3",
        dayNumber: 3,
        title: "Ganpatipule to Chiplun",
        date: undefined,
        summary: "~100 km ride exploring Ratnagiri, a cave shrine, and river confluence towns.",
        activities: [
          { _key: "pkr3a", title: "Ratnagiri", description: "Ratnagiri (Ratnadurg) Fort, Thibaw Palace, and Bhatye beach. Try local Alphonso mangoes if in season.", location: { name: "Ratnagiri", lat: 16.9902, lng: 73.312 }, type: "sightseeing" },
          { _key: "pkr3b", title: "Marleshwar", description: "Cave shrine plus a waterfall at the base of the Sahyadri hills — a short trek.", location: { name: "Marleshwar", lat: 17.0754, lng: 73.7431 }, type: "sightseeing" },
          { _key: "pkr3c", title: "Sangameshwar", description: "River confluence town with a temple stop.", location: { name: "Sangameshwar", lat: 17.1856, lng: 73.5597 }, type: "sightseeing" },
          { _key: "pkr3d", title: "Overnight at Chiplun", description: "Riverside town on the Vashishti river.", location: { name: "Chiplun", lat: 17.5332, lng: 73.5186 }, type: "accommodation" },
        ],
      },
      {
        _key: "pkr-day4",
        dayNumber: 4,
        title: "Chiplun to Pune via Raigad",
        date: undefined,
        summary: "~200 km return journey featuring the historic Raigad Fort.",
        activities: [
          { _key: "pkr4a", title: "Mahad", description: "Base town for Raigad Fort.", location: { name: "Mahad", lat: 18.0833, lng: 73.4167 }, type: "transport" },
          { _key: "pkr4b", title: "Raigad Fort", description: "Shivaji Maharaj's capital — take the ropeway or the ~1,400-step trek to the top. Worth a half-day.", location: { name: "Raigad Fort", lat: 18.2341, lng: 73.4464 }, type: "sightseeing" },
          { _key: "pkr4c", title: "Pune", description: "Ride back, arriving in the evening.", location: { name: "Pune", lat: 18.5204, lng: 73.8567 }, type: "transport" },
        ],
      },
    ],
  },
];


export const DEMO_AUTHOR: Author = {
  _id: "author-sumit",
  name: "Sumit Singh",
  slug: "sumit-singh",
  bio: "Travel writer, photographer, and software engineer. I document the roads less taken — high-altitude deserts, ancient monasteries, and everything in between. Based in India, always en route somewhere.",
  socialLinks: [
    { platform: "instagram", url: "https://instagram.com" },
    { platform: "twitter", url: "https://twitter.com" },
  ],
};

export async function getAllTrips(): Promise<Trip[]> {
  return DEMO_TRIPS;
}

export async function getTripBySlug(slug: string): Promise<Trip | null> {
  const trip = DEMO_TRIPS.find((t) => t.slug === slug);
  return trip || null;
}

export async function getTripsByRegion(regionSlug: string): Promise<Trip[]> {
  return DEMO_TRIPS.filter((t) => t.tags?.map(t => t.toLowerCase()).includes(regionSlug.replace(/-/g, " ")));
}

export async function getFeaturedTrips(): Promise<Trip[]> {
  return DEMO_TRIPS.slice(0, 3);
}

export async function searchTrips(queryText: string): Promise<Trip[]> {
  const lower = queryText.toLowerCase();
  return DEMO_TRIPS.filter((t) => 
    t.title.toLowerCase().includes(lower) || 
    (t.excerpt && t.excerpt.toLowerCase().includes(lower)) || 
    (t.tags && t.tags.some(tag => tag.toLowerCase().includes(lower)))
  );
}

export async function incrementViewCount(slug: string): Promise<void> {
  // Mock no-op since Sanity is removed
}
