"use client";

import { useState } from "react";
import { Download, Loader2 } from "lucide-react";
import type { GeneratedTrip } from "@/components/providers/GeneratedTripsProvider";

const btnStyle = {
  display: "inline-flex",
  alignItems: "center",
  gap: "6px",
  padding: "0.6rem 1rem",
  borderRadius: "var(--radius-sm)",
  background: "var(--bg-card)",
  color: "var(--text-secondary)",
  border: "1px solid var(--border)",
  fontSize: "0.85rem",
  fontFamily: "var(--font-sans)",
  cursor: "pointer",
  transition: "all var(--transition)",
};

interface ExportPDFButtonProps {
  trip: GeneratedTrip;
  variant?: "outline" | "ghost";
}

export default function ExportPDFButton({ trip, variant = "outline" }: ExportPDFButtonProps) {
  const [loading, setLoading] = useState(false);

  const handleExport = async () => {
    if (loading) return;
    setLoading(true);

    try {
      const { pdf, Document, Page, Text, View, StyleSheet } = await import("@react-pdf/renderer");

      const styles = StyleSheet.create({
        page: { padding: 40, fontFamily: "Helvetica", backgroundColor: "#ffffff" },
        header: { marginBottom: 24 },
        title: { fontSize: 24, fontWeight: "bold", marginBottom: 12, color: "#111827" },
        overview: { fontSize: 12, color: "#4B5563", marginBottom: 16, lineHeight: 1.6 },
        meta: { fontSize: 10, color: "#6B7280", marginBottom: 20 },
        dayContainer: { marginBottom: 20, padding: 16, border: "1pt solid #E5E7EB", borderRadius: 6, backgroundColor: "#F9FAFB" },
        dayHeader: { fontSize: 14, fontWeight: "bold", marginBottom: 6, color: "#111827" },
        daySummary: { fontSize: 11, fontStyle: "italic", color: "#4B5563", marginBottom: 12 },
        activity: { marginBottom: 12 },
        activityHeader: { fontSize: 11, fontWeight: "bold", color: "#111827", marginBottom: 4 },
        activityTime: { fontSize: 10, color: "#C9A84C", marginRight: 8 },
        activityDesc: { fontSize: 10, color: "#4B5563", lineHeight: 1.5 },
        activityNotes: { fontSize: 10, color: "#D97706", marginTop: 4, fontStyle: "italic" },
        footer: { position: "absolute", bottom: 30, left: 40, right: 40, textAlign: "center", color: "grey", fontSize: 10 },
      });

      const doc = (
        <Document>
          <Page size="A4" style={styles.page}>
            <View style={styles.header}>
              <Text style={styles.title}>{trip.title}</Text>
              {trip.overview && <Text style={styles.overview}>{trip.overview}</Text>}
              <Text style={styles.meta}>
                {trip.destination} • {trip.days?.length || 0} Days • {trip.month}
                {trip.totalBudgetEstimate ? ` • Budget: ${trip.totalBudgetEstimate}` : ""}
              </Text>
            </View>

            {trip.days?.map((day) => (
              <View key={day.dayNumber} style={styles.dayContainer} wrap={false}>
                <Text style={styles.dayHeader}>
                  Day {day.dayNumber}: {day.title}
                </Text>
                {day.summary && <Text style={styles.daySummary}>{day.summary}</Text>}

                {day.activities?.map((act, i) => (
                  <View key={i} style={styles.activity}>
                    <Text style={styles.activityHeader}>
                      {act.time && <Text style={styles.activityTime}>{act.time} </Text>}
                      {act.title}
                    </Text>
                    {act.description && <Text style={styles.activityDesc}>{act.description}</Text>}
                    {act.notes && <Text style={styles.activityNotes}>💡 {act.notes}</Text>}
                  </View>
                ))}
              </View>
            ))}
            <Text style={styles.footer} fixed>Generated by AI Trip Planner - Raste Aur Raahein</Text>
          </Page>
        </Document>
      );

      const blob = await pdf(doc).toBlob();
      const fileName = `${trip.title.replace(/\s+/g, "_").toLowerCase()}_itinerary.pdf`;
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = fileName;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("PDF export error:", err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={loading}
      style={{
        ...btnStyle,
        opacity: loading ? 0.7 : 1,
        background: variant === "ghost" ? "none" : "var(--bg-card)",
        border: variant === "ghost" ? "none" : "1px solid var(--border)",
      }}
      onMouseEnter={(e) => {
        if (!loading) {
          e.currentTarget.style.color = "var(--accent-gold)";
          e.currentTarget.style.borderColor = variant === "ghost" ? "transparent" : "var(--accent-gold)";
          if (variant === "ghost") e.currentTarget.style.background = "rgba(201,168,76,0.08)";
        }
      }}
      onMouseLeave={(e) => {
        if (!loading) {
          e.currentTarget.style.color = "var(--text-secondary)";
          e.currentTarget.style.borderColor = variant === "ghost" ? "transparent" : "var(--border)";
          if (variant === "ghost") e.currentTarget.style.background = "none";
        }
      }}
    >
      {loading ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}
      {loading ? "Preparing PDF..." : "Export to PDF"}
    </button>
  );
}
