"use client";

import { useState } from "react";
import { Share2, Loader2, Check, Copy } from "lucide-react";
import { useAuth } from "@/components/providers/AuthProvider";
import type { GeneratedTrip } from "@/components/providers/GeneratedTripsProvider";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

// ---------------------------------------------------------------------------
// PDF document styles (mirrored from ExportPDFButton)
// ---------------------------------------------------------------------------
const pdfStyles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", backgroundColor: "#ffffff" },
  header: { marginBottom: 24 },
  title: { fontSize: 24, fontWeight: "bold", marginBottom: 12, color: "#111827" },
  overview: { fontSize: 12, color: "#4B5563", marginBottom: 16, lineHeight: 1.6 },
  meta: { fontSize: 10, color: "#6B7280", marginBottom: 20 },
  dayContainer: {
    marginBottom: 20,
    padding: 16,
    border: "1pt solid #E5E7EB",
    borderRadius: 6,
    backgroundColor: "#F9FAFB",
  },
  dayHeader: { fontSize: 14, fontWeight: "bold", marginBottom: 6, color: "#111827" },
  daySummary: { fontSize: 11, fontStyle: "italic", color: "#4B5563", marginBottom: 12 },
  activity: { marginBottom: 12 },
  activityHeader: { fontSize: 11, fontWeight: "bold", color: "#111827", marginBottom: 4 },
  activityTime: { fontSize: 10, color: "#C9A84C", marginRight: 8 },
  activityDesc: { fontSize: 10, color: "#4B5563", lineHeight: 1.5 },
  activityNotes: { fontSize: 10, color: "#D97706", marginTop: 4, fontStyle: "italic" },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    color: "grey",
    fontSize: 10,
  },
});

// ---------------------------------------------------------------------------
// PDF document component
// ---------------------------------------------------------------------------
const ItineraryDocument = ({ trip }: { trip: GeneratedTrip }) => (
  <Document>
    <Page size="A4" style={pdfStyles.page}>
      <View style={pdfStyles.header}>
        <Text style={pdfStyles.title}>{trip.title}</Text>
        {trip.overview && <Text style={pdfStyles.overview}>{trip.overview}</Text>}
        <Text style={pdfStyles.meta}>
          {trip.destination} • {trip.days?.length || 0} Days • {trip.month}
          {trip.totalBudgetEstimate ? ` • Budget: ${trip.totalBudgetEstimate}` : ""}
        </Text>
      </View>

      {trip.days?.map((day) => (
        <View key={day.dayNumber} style={pdfStyles.dayContainer} wrap={false}>
          <Text style={pdfStyles.dayHeader}>
            Day {day.dayNumber}: {day.title}
          </Text>
          {day.summary && <Text style={pdfStyles.daySummary}>{day.summary}</Text>}

          {day.activities?.map((act, i) => (
            <View key={i} style={pdfStyles.activity}>
              <Text style={pdfStyles.activityHeader}>
                {act.time && <Text style={pdfStyles.activityTime}>{act.time} </Text>}
                {act.title}
              </Text>
              {act.description && (
                <Text style={pdfStyles.activityDesc}>{act.description}</Text>
              )}
              {act.notes && (
                <Text style={pdfStyles.activityNotes}>💡 {act.notes}</Text>
              )}
            </View>
          ))}
        </View>
      ))}
      <Text style={pdfStyles.footer} fixed>
        Generated by AI Trip Planner - Raste Aur Raahein
      </Text>
    </Page>
  </Document>
);

// ---------------------------------------------------------------------------
// Plain-text builder for non-logged-in users
// ---------------------------------------------------------------------------
function buildTextContent(trip: GeneratedTrip): string {
  const lines: string[] = [];
  lines.push(`✈️  ${trip.title}`);
  lines.push(`📍 ${trip.destination} • ${trip.days?.length || 0} Days • ${trip.month}`);
  if (trip.totalBudgetEstimate) lines.push(`💰 Budget: ${trip.totalBudgetEstimate}`);
  if (trip.bestTimeToVisit) lines.push(`🗓️  Best time: ${trip.bestTimeToVisit}`);
  if (trip.overview) {
    lines.push("");
    lines.push(trip.overview);
  }
  lines.push("");
  lines.push("─".repeat(40));

  trip.days?.forEach((day) => {
    lines.push("");
    lines.push(`📅 Day ${day.dayNumber}: ${day.title}`);
    if (day.summary) lines.push(`   ${day.summary}`);
    day.activities?.forEach((act) => {
      const time = act.time ? `[${act.time}] ` : "";
      lines.push(`   • ${time}${act.title}`);
      if (act.description) lines.push(`     ${act.description}`);
      if (act.notes) lines.push(`     💡 ${act.notes}`);
    });
  });

  lines.push("");
  lines.push("─".repeat(40));
  lines.push("Generated by AI Trip Planner – Raste Aur Raahein");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------
interface ShareItineraryButtonProps {
  trip: GeneratedTrip;
  variant?: "outline" | "ghost";
}

type ShareState = "idle" | "generating" | "shared" | "copied" | "error";

export default function ShareItineraryButton({
  trip,
  variant = "outline",
}: ShareItineraryButtonProps) {
  const { user } = useAuth();
  const [state, setState] = useState<ShareState>("idle");
  const [tooltip, setTooltip] = useState("");

  const isLoggedIn = !!user;
  const canShare = typeof navigator !== "undefined" && !!navigator.share;

  const handleShare = async () => {
    if (state === "generating") return;
    setState("generating");
    setTooltip("");

    try {
      if (isLoggedIn) {
        // ── Logged-in: share as PDF ──────────────────────────────────────
        const { pdf } = await import("@react-pdf/renderer");
        const blob = await pdf(<ItineraryDocument trip={trip} />).toBlob();
        const fileName = `${trip.title.replace(/\s+/g, "_").toLowerCase()}_itinerary.pdf`;
        const file = new File([blob], fileName, { type: "application/pdf" });

        if (canShare && navigator.canShare?.({ files: [file] })) {
          await navigator.share({
            title: trip.title,
            text: `Check out my ${trip.days?.length || 0}-day itinerary to ${trip.destination}!`,
            files: [file],
          });
        } else {
          // Fallback: trigger download if sharing not supported
          const url = URL.createObjectURL(blob);
          const a = document.createElement("a");
          a.href = url;
          a.download = fileName;
          a.click();
          URL.revokeObjectURL(url);
          setTooltip("PDF downloaded — share it manually");
        }
        setState("shared");
      } else {
        // ── Guest: share as text file ────────────────────────────────────
        const textContent = buildTextContent(trip);
        const fileName = `${trip.title.replace(/\s+/g, "_").toLowerCase()}_itinerary.txt`;
        const blob = new Blob([textContent], { type: "text/plain" });
        const file = new File([blob], fileName, { type: "text/plain" });

        if (canShare && navigator.canShare?.({ files: [file] })) {
          await navigator.share({
            title: trip.title,
            text: `Check out my ${trip.days?.length || 0}-day itinerary to ${trip.destination}!`,
            files: [file],
          });
          setState("shared");
        } else if (canShare) {
          // Share text without file (some browsers don't support file sharing)
          await navigator.share({
            title: trip.title,
            text: textContent,
          });
          setState("shared");
        } else {
          // Fallback: copy to clipboard
          await navigator.clipboard.writeText(textContent);
          setState("copied");
          setTooltip("Itinerary copied to clipboard!");
          setTimeout(() => setState("idle"), 2500);
          return;
        }

        setTimeout(() => setState("idle"), 3000);
      }
    } catch (err: unknown) {
      // User cancelled share — silently reset to idle
      if (err instanceof DOMException && err.name === "AbortError") {
        setState("idle");
        return;
      }
      // Real error: fall back to clipboard
      try {
        const textContent = buildTextContent(trip);
        await navigator.clipboard.writeText(textContent);
        setState("copied");
        setTooltip("Couldn't share — copied to clipboard instead!");
      } catch {
        setState("error");
        setTooltip("Could not share. Please try again.");
      }
      setTimeout(() => setState("idle"), 3000);
    }
  };

  // ── Derived display values ────────────────────────────────────────────────
  const Icon =
    state === "generating"
      ? Loader2
      : state === "shared" || state === "copied"
      ? Check
      : state === "error"
      ? Copy
      : Share2;

  const label =
    state === "generating"
      ? isLoggedIn
        ? "Preparing PDF…"
        : "Preparing…"
      : state === "shared"
      ? "Shared!"
      : state === "copied"
      ? "Copied!"
      : state === "error"
      ? "Failed"
      : "Share";

  const isSuccess = state === "shared" || state === "copied";
  const isSpinning = state === "generating";

  const borderColor = isSuccess
    ? "rgba(16,185,129,0.35)"
    : variant === "ghost"
    ? "transparent"
    : "var(--border)";

  const bgColor = isSuccess
    ? "rgba(16,185,129,0.12)"
    : variant === "ghost"
    ? "none"
    : "var(--bg-card)";

  const textColor = isSuccess
    ? "#10b981"
    : state === "error"
    ? "var(--accent-rose)"
    : "var(--text-secondary)";

  return (
    <div
      style={{
        position: "relative",
        display: "inline-flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "4px",
      }}
    >
      <button
        id="share-itinerary-btn"
        onClick={handleShare}
        disabled={state === "generating"}
        title={
          isLoggedIn
            ? "Share itinerary as PDF"
            : "Share itinerary as text (sign in for PDF)"
        }
        style={{
          display: "inline-flex",
          alignItems: "center",
          gap: "6px",
          padding: "0.6rem 1rem",
          borderRadius: "var(--radius-sm)",
          fontSize: "0.85rem",
          fontFamily: "var(--font-sans)",
          fontWeight: 500,
          cursor: state === "generating" ? "default" : "pointer",
          transition: "all var(--transition)",
          background: bgColor,
          color: textColor,
          border: `1px solid ${borderColor}`,
        }}
        onMouseEnter={(e) => {
          if (state === "idle") {
            e.currentTarget.style.color = "var(--accent-gold)";
            e.currentTarget.style.borderColor =
              variant === "ghost" ? "transparent" : "var(--accent-gold)";
            if (variant === "ghost")
              e.currentTarget.style.background = "rgba(201,168,76,0.08)";
          }
        }}
        onMouseLeave={(e) => {
          if (state === "idle") {
            e.currentTarget.style.color = "var(--text-secondary)";
            e.currentTarget.style.borderColor = borderColor;
            if (variant === "ghost") e.currentTarget.style.background = "none";
          }
        }}
      >
        <Icon
          size={14}
          style={
            isSpinning ? { animation: "share-btn-spin 1s linear infinite" } : undefined
          }
        />
        {label}

        {/* Badge: PDF or TXT */}
        {state === "idle" && (
          <span
            style={{
              fontSize: "0.58rem",
              padding: "1px 5px",
              borderRadius: "100px",
              fontWeight: 700,
              letterSpacing: "0.04em",
              ...(isLoggedIn
                ? {
                    background: "var(--accent-gold-dim)",
                    color: "var(--accent-gold)",
                    border: "1px solid var(--border-accent)",
                  }
                : {
                    background: "var(--bg-secondary)",
                    color: "var(--text-muted)",
                    border: "1px solid var(--border)",
                  }),
            }}
          >
            {isLoggedIn ? "PDF" : "TXT"}
          </span>
        )}
      </button>

      {/* Floating tooltip */}
      {tooltip && (
        <div
          style={{
            position: "absolute",
            top: "110%",
            left: "50%",
            transform: "translateX(-50%)",
            background: "var(--bg-card)",
            border: "1px solid var(--border)",
            borderRadius: "var(--radius-sm)",
            padding: "0.3rem 0.65rem",
            fontSize: "0.72rem",
            color: "var(--text-secondary)",
            whiteSpace: "nowrap",
            boxShadow: "var(--shadow-sm)",
            zIndex: 10,
            animation: "fadeIn 0.2s ease",
          }}
        >
          {tooltip}
        </div>
      )}

      <style>{`
        @keyframes share-btn-spin {
          from { transform: rotate(0deg); }
          to   { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
}
