import Link from "next/link";
import { Sparkles, Compass, ShieldCheck, MapPin, Download } from "lucide-react";

export default function PlanTripCTA() {
  return (
    <section
      aria-label="Trip planning options"
      style={{
        padding: "0 1.5rem 3rem",
        maxWidth: "1280px",
        margin: "0 auto",
      }}
    >
      <div
        style={{
          borderRadius: "1.25rem",
          background: "linear-gradient(135deg, #111318 0%, #1a1e28 50%, #111827 100%)",
          padding: "clamp(2rem, 5vw, 3.5rem)",
          position: "relative",
          overflow: "hidden",
          boxShadow: "0 20px 45px -10px rgba(0,0,0,0.35)",
          border: "1px solid rgba(255,255,255,0.08)",
        }}
      >
        {/* Ambient glow backgrounds */}
        <div
          aria-hidden="true"
          style={{
            position: "absolute",
            top: "-80px",
            right: "-60px",
            width: "320px",
            height: "320px",
            borderRadius: "50%",
            background: "radial-gradient(circle, rgba(201,168,76,0.18) 0%, rgba(99,102,241,0.05) 50%, transparent 70%)",
            filter: "blur(40px)",
            pointerEvents: "none",
          }}
        />
        <div
          aria-hidden="true"
          style={{
            position: "absolute",
            bottom: "-60px",
            left: "10%",
            width: "260px",
            height: "260px",
            borderRadius: "50%",
            background: "radial-gradient(circle, rgba(99,102,241,0.14) 0%, transparent 70%)",
            filter: "blur(40px)",
            pointerEvents: "none",
          }}
        />

        <div style={{ position: "relative", zIndex: 1, maxWidth: "800px" }}>
          {/* Eyebrow badge */}
          <div
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: "0.5rem",
              padding: "0.35rem 0.85rem",
              borderRadius: "9999px",
              background: "rgba(201,168,76,0.12)",
              border: "1px solid rgba(201,168,76,0.25)",
              color: "#f3c766",
              fontSize: "0.75rem",
              fontWeight: 700,
              textTransform: "uppercase",
              letterSpacing: "0.1em",
              marginBottom: "1.25rem",
            }}
          >
            <Sparkles size={13} />
            <span>Interactive Travel Tools</span>
          </div>

          <h2
            style={{
              fontSize: "clamp(1.75rem, 3.5vw, 2.75rem)",
              fontWeight: 800,
              letterSpacing: "-0.03em",
              lineHeight: 1.2,
              color: "#ffffff",
              margin: "0 0 1rem",
              fontFamily: "'Source Serif 4', Georgia, serif",
            }}
          >
            Ready to turn wanderlust into your next great expedition?
          </h2>

          <p
            style={{
              fontSize: "clamp(0.95rem, 1.8vw, 1.1rem)",
              color: "rgba(255,255,255,0.78)",
              lineHeight: 1.7,
              margin: "0 0 2rem",
            }}
          >
            Whether you want an instant day-by-day route generated by our custom AI planner,
            ground-verified road pass status, or complete GPX tracks for offline navigation,
            we have everything you need for India&apos;s wildest highways.
          </p>

          {/* Action buttons */}
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: "1rem",
              flexWrap: "wrap",
              marginBottom: "2.5rem",
            }}
          >
            <Link
              href="/ai-planner"
              id="cta-launch-ai-planner"
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: "0.625rem",
                padding: "0.95rem 1.75rem",
                borderRadius: "0.75rem",
                background: "linear-gradient(135deg, #c9a84c 0%, #e0b85c 100%)",
                color: "#0a0a0f",
                fontWeight: 700,
                fontSize: "0.9375rem",
                textDecoration: "none",
                boxShadow: "0 4px 20px rgba(201,168,76,0.35)",
                transition: "transform 0.2s ease, box-shadow 0.2s ease",
              }}
            >
              <Sparkles size={17} />
              <span>Launch AI Trip Planner</span>
            </Link>

            <Link
              href="/trips"
              id="cta-browse-all-guides"
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: "0.625rem",
                padding: "0.95rem 1.75rem",
                borderRadius: "0.75rem",
                background: "rgba(255,255,255,0.08)",
                border: "1px solid rgba(255,255,255,0.16)",
                color: "#ffffff",
                fontWeight: 600,
                fontSize: "0.9375rem",
                textDecoration: "none",
                backdropFilter: "blur(8px)",
                transition: "background 0.2s ease, border-color 0.2s ease",
              }}
            >
              <Compass size={17} />
              <span>Browse All Guides</span>
            </Link>

            <Link
              href="/road-conditions"
              id="cta-check-pass-status"
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: "0.5rem",
                padding: "0.95rem 1.25rem",
                color: "#94a3b8",
                fontWeight: 600,
                fontSize: "0.875rem",
                textDecoration: "underline",
                textUnderlineOffset: "4px",
                transition: "color 0.2s ease",
              }}
            >
              Check Mountain Pass Live Status →
            </Link>
          </div>

          {/* Trust proof indicators */}
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
              gap: "1.25rem",
              paddingTop: "1.75rem",
              borderTop: "1px solid rgba(255,255,255,0.1)",
            }}
          >
            <div style={{ display: "flex", alignItems: "center", gap: "0.75rem" }}>
              <div
                style={{
                  width: "32px",
                  height: "32px",
                  borderRadius: "8px",
                  background: "rgba(201,168,76,0.15)",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  color: "#f3c766",
                  flexShrink: 0,
                }}
              >
                <MapPin size={16} />
              </div>
              <span style={{ fontSize: "0.8125rem", color: "rgba(255,255,255,0.8)", fontWeight: 500 }}>
                60,000+ km Documented
              </span>
            </div>

            <div style={{ display: "flex", alignItems: "center", gap: "0.75rem" }}>
              <div
                style={{
                  width: "32px",
                  height: "32px",
                  borderRadius: "8px",
                  background: "rgba(99,102,241,0.15)",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  color: "#818cf8",
                  flexShrink: 0,
                }}
              >
                <Download size={16} />
              </div>
              <span style={{ fontSize: "0.8125rem", color: "rgba(255,255,255,0.8)", fontWeight: 500 }}>
                Offline GPX &amp; PDF Packs
              </span>
            </div>

            <div style={{ display: "flex", alignItems: "center", gap: "0.75rem" }}>
              <div
                style={{
                  width: "32px",
                  height: "32px",
                  borderRadius: "8px",
                  background: "rgba(34,197,94,0.15)",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  color: "#4ade80",
                  flexShrink: 0,
                }}
              >
                <ShieldCheck size={16} />
              </div>
              <span style={{ fontSize: "0.8125rem", color: "rgba(255,255,255,0.8)", fontWeight: 500 }}>
                BRO &amp; Police Verified Alerts
              </span>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
